Repository Alfresco/alfresco-content-app, pull requests merged in 2020-09, with the labels that each got.

#1663 change plugin
  e2e/e2e-config/utils/build-number.js
  e2e/e2e-config/utils/upload-output.js
  package-lock.json
  package.json
  protractor.conf.js
Labels: PR: reviewed-approved

#1672 Fix failing unit tests
  src/app/testing/app-testing.module.ts
Labels: PR: partially-approved

#1671 [ACA-2847] remove broken links to ACA code
  docs/extending/extension-format.md
  docs/features/document-list-layout.md
  docs/features/header.md
  docs/features/side-navigation.md
  docs/features/user-interface-layout.md
  docs/ja/features/document-list-layout.md
  docs/ja/features/header.md
  docs/ja/features/side-navigation.md
  docs/ja/features/user-interface-layout.md
Labels: PR: partially-approved

#1650 [ACA-3914] Fix app version number and enable git commit hash to be us…
  .vscode/settings.json
  package.json
  projects/aca-about/src/lib/about.component.html
  projects/aca-about/src/lib/about.component.ts
  tsconfig.base.json
Labels: PR: partially-approved

#1669 ACA Run the test against the remote env
  .gitignore
  .travis.yml
  e2e/e2e-config/utils/upload-output.js
  e2e/protractor.excludes.json
  e2e/suites/actions-available/files-folders/files-folders-actions.test.ts
  e2e/suites/actions-available/libraries/library.test.ts
  e2e/suites/actions-available/libraries/test-data-libraries.ts
  e2e/suites/actions-available/special-permissions/special-permissions-actions.test.ts
  e2e/suites/actions/copy-move/copy.test.ts
  e2e/suites/actions/copy-move/move.test.ts
  e2e/suites/actions/delete-undo-delete.test.ts
  e2e/suites/actions/download.test.ts
  e2e/suites/actions/edit-folder.test.ts
  e2e/suites/actions/edit-offline.test.ts
  e2e/suites/actions/library-actions.test.ts
  e2e/suites/actions/mark-favorite.test.ts
  e2e/suites/actions/share-file.test.ts
  e2e/suites/actions/unshare-file-search-results.test.ts
  e2e/suites/actions/unshare-file.test.ts
  e2e/suites/actions/upload-new-version.test.ts
  e2e/suites/info-drawer/comments.test.ts
  e2e/suites/list-views/permissions.test.ts
  e2e/suites/list-views/shared-files.test.ts
  e2e/suites/list-views/tooltips.test.ts
  e2e/suites/list-views/trash.test.ts
  e2e/suites/navigation/breadcrumb.test.ts
  e2e/suites/navigation/single-click.test.ts
  e2e/suites/pagination/favorites.ts
  e2e/suites/pagination/multiple-pages-files.test.ts
  e2e/suites/pagination/multiple-pages-libraries.test.ts
  e2e/suites/pagination/multiple-pages-trash.test.ts
  e2e/suites/pagination/personal-files.ts
  e2e/suites/pagination/recent-files.ts
  e2e/suites/pagination/search-results.ts
  e2e/suites/pagination/shared-files.ts
  e2e/suites/pagination/single-page.test.ts
  e2e/suites/viewer/viewer-actions.test.ts
  e2e/suites/viewer/viewer-general.test.ts
  package-lock.json
  package.json
  projects/aca-testing-shared/src/components/data-table/data-table.ts
  projects/aca-testing-shared/src/pages/page.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/favorites/favorites-api.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/queries/queries-api.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/search/search-api.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/shared-links/shared-links-api.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/sites/sites-api.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/trashcan/trashcan-api.ts
  projects/aca-testing-shared/src/utilities/utils.ts
  protractor.conf.js
  sanity-check.sh
  scripts/app-config-replace.js
  scripts/ci/jobs/affected-project-with.sh
Labels: PR: unreviewed

#1657 [ACA-3907] Document list header should not appear on an empty list
  projects/aca-testing-shared/src/components/data-table/data-table.ts
  src/app/components/page.component.ts
Labels: PR: unreviewed

#1689 [ACA-3902] Toolbar - Share button doesn't have an aria-label
  src/app/components/common/toggle-shared/toggle-shared.component.html
  src/app/components/common/toggle-shared/toggle-shared.component.spec.ts
  src/app/components/common/toggle-shared/toggle-shared.component.ts
Labels: PR: partially-approved

#1685 [ACA-3971] Added lightweight blank page to ACA for the sake of e2es
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/components/blank-page/blank-page.component.ts
Labels: PR: partially-approved

#1691 [ADF-5257] Refactor Document list header filters
  e2e/suites/navigation/single-click.test.ts
  package-lock.json
  package.json
  src/app/components/files/files.component.html
  src/app/components/files/files.component.ts
  src/app/components/page.component.spec.ts
  src/app/components/page.component.ts
Labels: PR: partially-approved

#1695 Fix FilterSearch import path
  src/app/components/files/files.component.ts
Labels: PR: partially-approved

#1696 Add blank route to public routes
  src/app.config.json
Labels: PR: unreviewed

#1692 [ACA-3916] Fix placeholder
  src/app.config.json
Labels: PR: reviewed-approved
