Repository Alfresco/alfresco-content-app, pull requests merged in 2020-05, with the labels that each got.

#1436 Update .travis.yml
  .travis.yml
Labels: PR: partially-approved

#1438 Updating Readme for release 1.11.0
  README.md
Labels: PR: partially-approved

#1439 [ACA-3238] automatically publish libraries on release
  .travis.yml
  projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.ts
  scripts/travis/release/release-npm.sh
Labels: PR: partially-approved

#1437 [ACA-3239] deprecate tomcat builds
  build-tomcat-e2e.sh
  docker/tomcat/Dockerfile
  docker/tomcat/artifacts/.gitignore
  docker/tomcat/artifacts/.gitkeep
  docker/tomcat/docker-compose.yml
  docker/tomcat/nginx.conf
  package.json
Labels: PR: unreviewed

#1441 bump and align lib versions with the app
  projects/aca-shared/package.json
  projects/adf-office-services-ext/package.json
Labels: PR: reviewed-changes-requested

#1442 Add tag end release
  .travis.yml
  scripts/travis/release/git-tag.sh
Labels: PR: partially-approved

#1443 license and audit info
  .prettierignore
  docs/audit/audit-info-1.11.0.md
  docs/licences/license-info-1.11.0.md
Labels: PR: partially-approved

#1444 upgrade to ADF 3.8.0 final
  package-lock.json
  package.json
Labels: PR: unreviewed

#1449 [ACA-3249] customisable header image url
  docs/getting-started/configuration.md
  projects/aca-shared/store/src/selectors/app.selectors.ts
  projects/aca-shared/store/src/states/app.state.ts
  src/app.config.json
  src/app/app.component.ts
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.ts
  src/app/store/initial-state.ts
  src/app/ui/custom-theme.scss
Labels: PR: partially-approved

#1457 Add missing documentation for extension loader callbacks
  .travis.yml
  .vscode/settings.json
  docs/extending/README.md
  docs/extending/custom-extension-loaders.md
  projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.ts
  scripts/ci/job_hooks/before_install.sh
  scripts/install.sh
  scripts/update-version.sh
Labels: PR: unreviewed

#1461 [e2e] fix flaky tests
  e2e/components/search/search-input.ts
  e2e/suites/actions/edit-folder.test.ts
  e2e/suites/actions/library-actions.test.ts
  e2e/utilities/utils.ts
  protractor.conf.js
Labels: PR: partially-approved

#1462 [ACA-3278] Header - extension actions not visible
  src/app/components/header/header.component.spec.ts
  src/app/components/toolbar/toolbar-action/toolbar-actions.component.scss
  src/app/ui/custom-theme.scss
Labels: PR: reviewed-approved

#1465 [AAE-2603] unified env variables for ecm/bpm hosts
  docker/entrypoint.sh
Labels: PR: partially-approved

#1469 [ACA-3251] DW prod build issue
  projects/aca-shared/src/lib/testing/lib-testing-module.ts
Labels: PR: reviewed-approved

#1470 Favorite remove the route evaluation
  package-lock.json
  package.json
  src/app/components/toolbar/toggle-favorite/toggle-favorite.component.ts
Labels: PR: unreviewed

#1464 [ACA-3296] Header - support actions order
  e2e/resources/extensibility-configs/header-ext.json
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  src/app/app.module.ts
  src/app/components/header/header.component.html
  src/app/components/toolbar/toolbar-action/toolbar-actions.component.scss
  src/app/extensions/core.extensions.module.ts
  src/assets/plugins/app.header.json
Labels: PR: reviewed-approved

#1471 [ACA-3257] Add actions extension capability to info drawer
  docs/extending/application-features.md
  docs/ja/extending/application-features.md
  e2e/resources/extensibility-configs/context-submenus-ext.json
  e2e/resources/extensibility-configs/document-presets-ext.json
  e2e/resources/extensibility-configs/extensions-default.json
  e2e/resources/extensibility-configs/header-ext.json
  e2e/resources/extensibility-configs/info-drawer-ext.json
  e2e/resources/extensibility-configs/metadata-ext.json
  e2e/resources/extensibility-configs/viewer-ext.json
  extension.schema.json
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.html
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.spec.ts
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.ts
  projects/aca-shared/src/lib/components/info-drawer/shared-info-drawer.module.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  src/assets/app.extensions.json
Labels: PR: unreviewed

#1472 [ACA-3317] Show app current deployed commit in About Page
  package-lock.json
  package.json
  scripts/update-commit-sha.sh
  src/app/components/about/about.component.html
  src/app/components/about/about.component.ts
Labels: PR: unreviewed

#1474 [ACA-1992] Keep favorite libraries navigation under same path
  projects/aca-shared/store/src/actions/library.actions.ts
  src/app/app.routes.ts
  src/app/components/favorite-libraries/favorite-libraries.component.spec.ts
  src/app/components/favorite-libraries/favorite-libraries.component.ts
  src/app/store/effects/library.effects.ts
Labels: PR: partially-approved

#1476 [ACA-3346] Fix build script
  .travis.yml
  package.json
  scripts/update-commit-sha.sh
Labels: PR: partially-approved

#1473 [ACA-2312] Fix inconsistency for My Libraries
  e2e/components/dialog/content-node-selector-dialog.ts
  e2e/configs.ts
  e2e/suites/actions/copy-move/copy.test.ts
  e2e/suites/actions/copy-move/destination-picker-dialog.test.ts
  e2e/suites/actions/copy-move/move.test.ts
  src/app/services/node-actions.service.ts
Labels: PR: unreviewed

#1475 [ACA-3342] Rename API_HOST to API_CONTENT_HOST
  docs/getting-started/building-from-source.md
  protractor.conf.js
  scripts/app-config-replace.js
  src/proxy.conf.js
Labels: PR: partially-approved

#1479 Use latest adf to fix issue 3252
  package-lock.json
  package.json
  projects/aca-shared/src/lib/directives/pagination.directive.spec.ts
  src/app/components/context-menu/context-menu.service.spec.ts
  src/app/components/dl-custom-components/name-column/name-column.component.spec.ts
  src/app/components/node-version/node-version-form.component.spec.ts
  src/app/components/search/search-results/search-results.component.spec.ts
  src/app/components/toolbar/toggle-edit-offline/toggle-edit-offline.component.spec.ts
  src/app/components/toolbar/toggle-favorite-library/toggle-favorite-library.component.spec.ts
  src/app/components/toolbar/toggle-favorite/toggle-favorite.component.spec.ts
  src/app/components/toolbar/view-node/view-node.component.spec.ts
  src/app/dialogs/node-template/create-from-template.dialog.spec.ts
  src/app/dialogs/node-version-upload/node-version-upload.dialog.spec.ts
  src/app/directives/library-favorite.directive.spec.ts
  src/app/directives/library-membership.directive.spec.ts
  src/app/directives/lock-node.directive.spec.ts
Labels: PR: partially-approved
