Repository Alfresco/alfresco-content-app, pull requests merged in 2020-06, with the labels that each got.

#1478 [ACA-3315] - add predefined extension guard
  docs/extending/routes.md
  projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.spec.ts
  projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.ts
  src/app/extensions/core.extensions.module.ts
Labels: PR: partially-approved

#1477 [ACA-45] Drag and Drop a new version
  e2e/suites/actions/upload-new-version.test.ts
  projects/aca-shared/store/src/actions/upload.actions.ts
  projects/aca-testing-shared/src/components/dialog/upload-new-version-dialog.ts
  src/app/app.module.ts
  src/app/components/files/files.component.html
  src/app/components/files/files.component.ts
  src/app/components/toolbar/toggle-favorite/toggle-favorite.component.spec.ts
  src/app/dialogs/node-version-upload/node-version-upload.dialog.html
  src/app/dialogs/node-version-upload/node-version-upload.dialog.scss
  src/app/dialogs/node-version-upload/node-version-upload.dialog.spec.ts
  src/app/dialogs/node-version-upload/node-version-upload.dialog.ts
  src/app/dialogs/node-versions/node-versions.dialog.html
  src/app/dialogs/node-versions/node-versions.dialog.spec.ts
  src/app/dialogs/node-versions/node-versions.dialog.theme.scss
  src/app/dialogs/node-versions/node-versions.dialog.ts
  src/app/services/content-management.service.spec.ts
  src/app/services/content-management.service.ts
  src/app/store/effects/upload.effects.spec.ts
  src/app/store/effects/upload.effects.ts
Labels: PR: partially-approved

#1485 [ACA-3450] Add missing documentation about parentRoute
  docs/extending/routes.md
Labels: PR: partially-approved

#1482 [ACA-2582]- fix: proper menuitem aria for screen reader users
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.html
Labels: PR: partially-approved

#1484 [ACA-3266] Improve version upload component
  package-lock.json
  package.json
  src/app/dialogs/node-versions/node-versions.dialog.html
  src/app/dialogs/node-versions/node-versions.dialog.spec.ts
  src/app/dialogs/node-versions/node-versions.dialog.theme.scss
Labels: PR: unreviewed

#1486 [ACS-180] Add Description column to My libraries / Favorites
  e2e/resources/extensibility-configs/info-drawer-ext.json
  e2e/resources/extensibility-configs/viewer-ext.json
  e2e/suites/list-views/file-libraries.test.ts
  e2e/suites/search/search-results-libraries.test.ts
  projects/aca-testing-shared/src/components/data-table/data-table.ts
  src/assets/app.extensions.json
  src/assets/i18n/en.json
Labels: PR: unreviewed

#1487 [MNT-21419] correctly reset search results
  .github/plint.yml
  package-lock.json
  package.json
  projects/aca-shared/src/lib/services/app.service.spec.ts
  projects/aca-shared/src/lib/services/app.service.ts
Labels: PR: unreviewed

#1489 MNT-18448 - Edit Online for MS Visio files
  projects/adf-office-services-ext/src/lib/utils.ts
Labels: PR: partially-approved

#1490 Edit Online for XLAM files
  projects/adf-office-services-ext/src/lib/utils.ts
Labels: PR: partially-approved

#1488 MNT-19466 - Edit Online for RTF files
  projects/adf-office-services-ext/src/lib/utils.ts
Labels: PR: reviewed-approved

#1492 [ACA-3469] Description in Document library Site
  src/assets/app.extensions.json
Labels: PR: unreviewed

#1491 [ACA-3427] Remove About tab when it's not useful
  docs/extending/rules.md
  e2e/suites/actions-available/libraries/test-data-libraries.ts
  e2e/suites/info-drawer/library-properties.test.ts
  projects/aca-shared/rules/src/app.rules.spec.ts
  projects/aca-shared/rules/src/app.rules.ts
  src/app/extensions/core.extensions.module.ts
  src/assets/app.extensions.json
Labels: PR: partially-approved

#1494 Use the latest adf
  package-lock.json
  package.json
Labels: PR: partially-approved

#1499 [ACA-3471] too long french translation doesn't fit in the UI
  src/assets/i18n/fr.json
Labels: PR: unreviewed

#1500 [ACA-3538] Fix search result layout
  src/app/components/search/search-results/search-results.component.scss
Labels: PR: reviewed-changes-requested

#1501 Release preparation
  docs/audit/audit-info-1.12.0.md
  docs/licences/license-info-1.12.0.md
  package-lock.json
  package.json
  projects/aca-shared/package.json
  projects/aca-testing-shared/package.json
  projects/adf-office-services-ext/package.json
Labels: PR: unreviewed

#1502 Update ADF packages version 3.9.0
  package-lock.json
  package.json
Labels: PR: partially-approved

#1503 update search docs
  docs/features/search-results.md
Labels: PR: partially-approved
