Repository Alfresco/alfresco-content-app, pull requests merged in 2020-04, with the labels that each got.

#1394 [ACA-2970] Change hover and select data row background color
  src/app/ui/custom-theme.scss
Labels: PR: partially-approved

#1395 [ACA-2604] Fix color update on datable row
  src/app/components/search/search-results-row/search-results-row.component.scss
Labels: PR: partially-approved

#1390 Use the e2e lite-serve
  .travis.yml
  angular.json
  docker-compose.e2e.yml
  docker/proxy/nginx.conf
  e2e/configs.ts
  e2e/pages/login-page.ts
  e2e/suites/actions/share-file.test.ts
  e2e/utilities/repo-client/apis/repo-api.ts
  e2e/utilities/repo-client/repo-client-models.ts
  e2e/utilities/repo-client/repo-client.ts
  package-lock.json
  package.json
  protractor.conf.js
  scripts/app-config-replace.js
  scripts/ci/job_hooks/before_e2e.sh
  start.sh
Labels: PR: partially-approved

#1396 [ACA-2979] Change create menu item colors
  src/app/components/create-menu/create-menu.component.scss
Labels: PR: partially-approved

#1373 upgrade to latest ADF alpha
  e2e/suites/actions/share-file.test.ts
  package-lock.json
  package.json
  src/app.config.json
Labels: PR: unreviewed

#1397 [ACA-2980] Update search input background-color
  src/app/components/search/search-input/search-input.component.theme.scss
Labels: PR: unreviewed

#1369 [ACA-2368] UI Issues while editing Metadata in the Preview Page
  src/app/components/info-drawer/info-drawer.component.ts
  src/app/components/viewer/viewer.component.html
  src/app/components/viewer/viewer.component.ts
Labels: PR: partially-approved

#1401 [E2E] try to fix one weird flaky test
  e2e/components/dialog/password-dialog.ts
  e2e/components/viewer/viewer.ts
  e2e/suites/viewer/viewer-protected-file.test.ts
Labels: PR: partially-approved

#1403 add missing color header action
  docs/extending/application-actions.md
  projects/aca-shared/store/src/actions/app.actions.ts
  src/app/store/reducers/app.reducer.ts
Labels: PR: partially-approved

#1404 upgrade dependencies
  package-lock.json
  package.json
Labels: PR: unreviewed

#1405 [ACA-2734] Be able to show an extension based on provider
  extension.schema.json
  package-lock.json
  package.json
  src/app/components/sidenav/sidenav.component.html
  src/app/components/sidenav/sidenav.component.ts
Labels: PR: unreviewed

#1408 [ACA-1743] improved settings api
  extension.schema.json
  src/app/components/settings/settings.component.ts
  src/app/extensions/extension.service.ts
  src/app/types.ts
  src/assets/app.extensions.json
Labels: PR: reviewed-approved

#1412 unified puppeteer setup
  .travis.yml
  package-lock.json
  package.json
  scripts/postinstall.sh
Labels: PR: unreviewed

#1413 [ACA-2948] Remove process services and AI extension from settings page
  projects/aca-shared/rules/src/app.rules.ts
  src/app/extensions/core.extensions.module.ts
  src/assets/app.extensions.json
Labels: PR: reviewed-approved

#1411 [ACA-3043] Create From Template - relativePath not working when ACS installation language is different
  src/app/services/node-template.service.spec.ts
  src/app/services/node-template.service.ts
  src/app/store/effects/template.effects.spec.ts
  src/app/store/effects/template.effects.ts
Labels: PR: reviewed-approved

#1414 [ACA-2496] Change hover color on custom name color
  src/app/components/dl-custom-components/name-column/name-column.component.scss
  src/app/ui/custom-theme.scss
Labels: PR: partially-approved

#1416 [ACA-2542] Change create menu colors
  src/app/components/create-menu/create-menu.component.scss
Labels: PR: partially-approved

#1417 use Logger instead of console
  e2e/components/data-table/data-table.ts
  e2e/components/info-drawer/info-drawer-metadata-library.ts
  e2e/components/info-drawer/info-drawer.ts
  e2e/components/menu/menu.ts
  e2e/components/pagination/pagination.ts
  e2e/components/sidenav/sidenav.ts
  e2e/components/viewer/viewer.ts
  e2e/pages/page.ts
  e2e/suites/application/general.test.ts
  e2e/utilities/repo-client/apis/favorites/favorites-api.ts
  e2e/utilities/repo-client/apis/queries/queries-api.ts
  e2e/utilities/repo-client/apis/repo-api.ts
  e2e/utilities/repo-client/apis/search/search-api.ts
  e2e/utilities/repo-client/apis/shared-links/shared-links-api.ts
  e2e/utilities/repo-client/apis/sites/sites-api.ts
  e2e/utilities/repo-client/apis/trashcan/trashcan-api.ts
  e2e/utilities/utils.ts
  package-lock.json
  package.json
  src/app/extensions/extension.service.ts
  src/main.ts
  tslint.json
Labels: PR: reviewed-approved

#1421 [ACA-3046] Create new folder window - missing 'Name'/'Description' la…
  .travis.yml
  package.json
Labels: PR: partially-approved

#1423 [ACA-3015] - fixed style for chips
  src/app/components/search/search-results/search-results.component.scss
Labels: PR: partially-approved

#1422 Update ADF packages version 3.8.0-beta9
  package-lock.json
  package.json
Labels: PR: unreviewed

#1424 [ACA-2496] Refactor of color change for colum name
  src/app/components/dl-custom-components/name-column/name-column.component.scss
Labels: PR: partially-approved

#1425 [ACA-3081] upgrade @types/jasmine to latest
  package-lock.json
  package.json
  projects/aca-shared/rules/src/app.rules.spec.ts
  src/app/components/context-menu/context-menu.service.ts
  src/app/components/favorite-libraries/favorite-libraries.component.spec.ts
  src/app/components/info-drawer/library-metadata-tab/library-metadata-form.component.spec.ts
  src/app/components/preview/preview.component.spec.ts
  src/app/components/recent-files/recent-files.component.spec.ts
  src/app/components/search/search-libraries-results/search-libraries-query-builder.service.spec.ts
  src/app/components/search/search-results/search-results.component.spec.ts
  src/app/extensions/extension.service.spec.ts
  src/app/extensions/extension.service.ts
  src/app/services/content-management.service.spec.ts
  src/app/services/content-management.service.ts
  src/app/services/node-actions.service.spec.ts
  src/app/services/node-actions.service.ts
  src/app/services/node-template.service.spec.ts
  src/app/store/effects/contextmenu.effects.spec.ts
  src/app/store/effects/template.effects.spec.ts
  src/app/store/effects/upload.effects.spec.ts
Labels: PR: reviewed-approved

#1429 [e2e] enable tests
  protractor.conf.js
Labels: PR: unreviewed

#1430 [ACA-3190] Update env from travis
  .travis.yml
  package.json
  scripts/install.sh
  scripts/travis/deploy/deploy.sh
  scripts/travis/deploy/get-docker-image-tag-name.sh
  scripts/travis/deploy/rancher-update.sh
  scripts/update-version.sh
Labels: PR: unreviewed

#1432 LOC-129 -fixes for UI strings in French and Dutch
  src/assets/i18n/fr.json
  src/assets/i18n/nl.json
Labels: PR: partially-approved

#1431 [ACA-2994] Snackbar- notifications are displayed with wrong colours
  src/app/ui/custom-theme.scss
Labels: PR: partially-approved

#1426 [ACA-3131] Add extension loader guard
  cspell.json
  projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.spec.ts
  projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.ts
  projects/aca-shared/src/public-api.ts
  src/app/app.routes.ts
Labels: PR: partially-approved

#1434 Update to latest ADF libraries
  package-lock.json
  package.json
Labels: PR: partially-approved

#1435 [ACA-3153] bump version to 1.11.0
  package-lock.json
  package.json
  src/app.config.json
Labels: PR: unreviewed
