Repository Alfresco/alfresco-content-app, pull requests merged in 2020-07, with the labels that each got.

#1504 remove bash scripts from postinstall
  package.json
  scripts/ci/job_hooks/before_e2e.sh
  scripts/update-webdriver.sh
Labels: PR: partially-approved

#1505 [ACA-3595] Fix broken extending navbar by using route id reference
  src/app/components/sidenav/directives/action.directive.spec.ts
  src/app/components/sidenav/directives/action.directive.ts
Labels: PR: partially-approved

#1509 [ADF-5178] - add translation for filters
  src/app.config.json
  src/assets/i18n/en.json
Labels: PR: partially-approved

#1510 Enable remaining tests
  e2e/suites/actions/new-menu.test.ts
Labels: PR: partially-approved

#1508 Copy screenshots to env
  e2e/e2e-config/hooks/after-launch.js
  e2e/e2e-config/utils/build-number.js
  e2e/e2e-config/utils/upload-output.js
  protractor.conf.js
Labels: PR: partially-approved, do not merge

#1512 fix i18n warnings and upgrade to Angular 10.0.3
  package-lock.json
  package.json
  src/app/app.module.ts
Labels: PR: partially-approved

#1528 [ACA-3670] Inconsistent empty role value between library views
  e2e/suites/actions/library-actions.test.ts
  package-lock.json
  package.json
  projects/aca-testing-shared/src/configs.ts
  src/app/services/node-actions.service.spec.ts
Labels: PR: unreviewed

#1536 upgrade 3rd party libs
  package-lock.json
  package.json
Labels: PR: unreviewed

#1526 Remove protractor noise plugin
  e2e/e2e-config/utils/upload-output.js
  package-lock.json
  package.json
  protractor.conf.js
Labels: PR: unreviewed

#1527 MNT-21595- Fetch all the groups
  package-lock.json
  package.json
  src/app/app.component.spec.ts
  src/app/app.component.ts
Labels: PR: partially-approved

#1547 [ACA-3752][ADW] Pagination values are not passed when a filter is app…
  src/app/components/files/files.component.html
  src/app/components/page.component.ts
Labels: PR: partially-approved

#1558 Update webdriver version
  protractor.conf.js
  scripts/ci/job_hooks/before_e2e.sh
Labels: PR: partially-approved

#1567 [ACA-3799] add prefix * name filter
  e2e/protractor.excludes.json
  e2e/suites/actions-available/files-folders/search-results.ts
  package-lock.json
  package.json
  protractor.conf.js
  src/app.config.json
Labels: PR: unreviewed

#1570 Fix smart runner
  .gitignore
  .travis.yml
  angular.json
  e2e/e2e-config/hooks/after-launch.js
  protractor.conf.js
Labels: PR: unreviewed
