Repository Alfresco/alfresco-content-app, pull requests merged in 2020-03, with the labels that each got.

#1357 [MNT-21394] Edit in Microsoft Office opens MS Excel documents then immediately prompts that a newer version exists
  package-lock.json
  package.json
  projects/aca-shared/src/lib/services/content-api.service.ts
  projects/adf-office-services-ext/src/lib/aos-extension.service.ts
Labels: PR: unreviewed

#1359 1.9.1 bump
  package-lock.json
  package.json
  projects/aca-shared/package.json
  projects/adf-office-services-ext/assets/aos.plugin.json
  projects/adf-office-services-ext/package.json
  src/app.config.json
Labels: PR: unreviewed

#1358 AAE-1690 run as non privileged user
  docker/nginx.conf
Labels: PR: reviewed-approved

#1360 bump
  projects/aca-shared/package.json
Labels: PR: reviewed-approved

#1363 fix for [MNT-21394]
  projects/aca-shared/src/lib/services/content-api.service.ts
  projects/adf-office-services-ext/src/lib/aos-extension.service.ts
Labels: PR: unreviewed

#1365 bump versions
  package-lock.json
  package.json
  projects/aca-shared/package.json
  projects/adf-office-services-ext/assets/aos.plugin.json
  projects/adf-office-services-ext/package.json
  src/app.config.json
Labels: PR: reviewed-approved

#1355 MNT-21394 Edit in Microsoft Office opens MS Excel documents then immediately prompts that a newer version exists
  projects/aca-shared/src/lib/services/content-api.service.ts
  projects/adf-office-services-ext/src/lib/aos-extension.service.ts
Labels: PR: unreviewed

#1366 [ACA-2123] New header background color for AA accessibility
  docs/getting-started/configuration.md
  docs/ja/getting-started/configuration.md
  src/app.config.json
  src/app/components/current-user/current-user.component.theme.scss
  src/app/store/initial-state.ts
Labels: PR: reviewed-approved

#1367 [ACA-2124] New bg-color and font style for "New" button
  src/app/components/create-menu/create-menu.component.scss
Labels: PR: reviewed-approved

#1368 [ACA-2125] Update sidenav colors and font-size
  projects/aca-shared/src/lib/components/page-layout/page-layout.component.scss
  src/app/components/sidenav/sidenav.component.theme.scss
  src/app/ui/custom-theme.scss
  src/app/ui/theme.scss
Labels: PR: reviewed-approved

#1315 [ACA-2582] menu menuitem roles
  src/app/components/create-menu/create-menu.component.html
  src/app/components/toolbar/toolbar-menu-item/toolbar-menu-item.component.html
Labels: PR: unreviewed

#1370 Revert "[ACA-2125] Update sidenav colors and font-size"
  projects/aca-shared/src/lib/components/page-layout/page-layout.component.scss
  src/app/components/sidenav/sidenav.component.theme.scss
  src/app/ui/custom-theme.scss
  src/app/ui/theme.scss
Labels: PR: unreviewed

#1374 [ACA-2948] Add process services extension in settings page
  projects/aca-shared/rules/src/app.rules.ts
  projects/aca-shared/store/src/actions/app.actions.ts
  projects/aca-shared/store/src/selectors/app.selectors.ts
  projects/aca-shared/store/src/states/app.state.ts
  src/app.config.json
  src/app/app.component.ts
  src/app/components/settings/settings.component.html
  src/app/components/settings/settings.component.theme.scss
  src/app/components/settings/settings.component.ts
  src/app/extensions/core.extensions.module.ts
  src/app/extensions/extension.service.ts
  src/app/store/initial-state.ts
  src/app/store/reducers/app.reducer.ts
Labels: PR: reviewed-approved

#1377 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: reviewed-approved

#1376 [ACA-2123] Change header colors
  docs/getting-started/configuration.md
  docs/ja/getting-started/configuration.md
  src/app.config.json
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.ts
  src/app/components/layout/layout.theme.scss
  src/app/store/initial-state.ts
Labels: PR: reviewed-approved

#1379 [ACA-2952] Remove unnecessary build steps for dev-server start, add first bit of .env usage
  .github/CODEOWNERS
  .gitignore
  angular.json
  docs/getting-started/building-from-source.md
  package-lock.json
  package.json
  src/proxy.conf.js
  tsconfig.json
Labels: PR: reviewed-approved

#1381 ACA - Fix import
  src/app/components/layout/layout.theme.scss
Labels: PR: reviewed-approved

#1380 [ACA-2604] Search result/input color update
  src/app/components/search/search-input/search-input.component.theme.scss
  src/app/components/search/search-results-row/search-results-row.component.scss
  src/app/ui/custom-theme.scss
Labels: PR: reviewed-approved

#1375 [ACA-2695] Change and refactor theme
  src/app/ui/application.scss
  src/app/ui/colors.scss
  src/app/ui/custom-theme.scss
  src/app/ui/theme.scss
Labels: PR: reviewed-approved

#1378 [ACA-2125] Update sidenav colors to meet design spec
  src/app/components/sidenav/sidenav.component.theme.scss
Labels: PR: reviewed-approved

#1382 Fix the scss import and save the build on S3
  .travis.yml
  package.json
  scripts/ci/job_hooks/before_install.sh
  scripts/ci/utils/artifact-from-s3.sh
  scripts/ci/utils/artifact-to-s3.sh
  src/app/components/layout/layout.theme.scss
  tsconfig.json
Labels: PR: unreviewed

#1384 trigger DW build after merge in development or master
  .travis.yml
  scripts/trigger-travis.sh
Labels: PR: reviewed-approved

#1385 upgrade date picker to 3.1.0
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#1386 [ACA-2959] Add new login background
  src/app/components/login/login.component.html
  src/assets/images/Wallpaper-BG-generic.svg
Labels: PR: reviewed-approved

#1387 Add build status badges
  README.md
Labels: PR: reviewed-approved

#1389 [ACA-2960] Add background image and elevation to header
  src/app/components/header/header.component.scss
  src/assets/images/mastHead-bg-shapesPattern.svg
Labels: PR: reviewed-approved

#1388 Trigger build only on branches
  .travis.yml
Labels: PR: unreviewed

#1391 upgrade codelyzer and enable a11y rules
  package-lock.json
  package.json
  src/app/components/context-menu/context-menu.component.html
  src/app/components/dl-custom-components/name-column/name-column.component.html
  src/app/components/search/search-results-row/search-results-row.component.html
  src/app/directives/library-favorite.directive.spec.ts
  src/app/directives/lock-node.directive.spec.ts
  tslint.json
Labels: PR: partially-approved

#1392 Fix: Use the absolute path
  src/app/components/header/header.component.scss
Labels: PR: partially-approved
