Repository Alfresco/alfresco-content-app, pull requests merged in 2020-08, with the labels that each got.

#1581 [ACA-3793] - Make e2e download folder path OS agnostic
  protractor.conf.js
Labels: PR: reviewed-approved

#1580 [ACA-3808] - fix e2e actionMenu
  e2e/suites/actions-available/test-util.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.html
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.spec.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.ts
Labels: PR: partially-approved

#1582 [ACA-3816] Metadata - get definition field
  projects/aca-shared/src/lib/services/content-api.service.ts
  src/app/directives/document-list.directive.ts
Labels: PR: partially-approved

#1496 [ACA-3394] Generally available file preview feature for extensions
  docs/extending/components.md
  docs/extending/routes.md
  docs/extending/tutorials.md
  package-lock.json
  package.json
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  projects/aca-shared/src/lib/services/router.extension.service.spec.ts
  projects/aca-shared/src/lib/services/router.extension.service.ts
  projects/aca-shared/src/public-api.ts
  projects/aca-shared/store/src/actions/viewer.actions.ts
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/components/preview/preview.component.html
  src/app/components/preview/preview.component.ts
  src/app/extensions/core.extensions.module.ts
  src/app/store/effects/viewer.effects.ts
Labels: PR: unreviewed

#1586 [ACA-3394] Fixing wrong rebase for file preview and exclude failing regressive e2es
  e2e/protractor.excludes.json
  src/app/store/effects/viewer.effects.ts
Labels: PR: unreviewed

#1584 [ACA-3821] Add lite-serve with VSCode launcher
  .gitignore
  .vscode/closest-config-finder.sh
  .vscode/launch.json
  angular.json
  package-lock.json
  package.json
  scripts/app-config-replace.js
  scripts/clireader/base-param.ts
  scripts/clireader/boolean-param.ts
  scripts/clireader/checkbox-param.ts
  scripts/clireader/cli-reader.ts
  scripts/clireader/input-param.ts
  scripts/clireader/list-param.ts
  scripts/clireader/params.ts
  scripts/npm/helpers/project-selectors.ts
  scripts/npm/lite-serve.ts
  scripts/run
  scripts/tsconfig.json
  tools/helpers/logger.js
Labels: PR: unreviewed

#1575 [ACA-3796] - fixed error on sorting
  e2e/resources/extensibility-configs/context-submenus-ext.json
  e2e/resources/extensibility-configs/document-presets-ext.json
  extension.schema.json
  package-lock.json
  package.json
  src/app/components/files/files.component.html
  src/app/components/files/files.component.spec.ts
  src/assets/app.extensions.json
Labels: PR: unreviewed

#1592 [ACA-3788] Viewer - toolbar disappears after refresh
  src/app/components/page.component.spec.ts
  src/app/components/page.component.ts
Labels: PR: partially-approved

#1593 [ACA-3593] fix library builds
  e2e/tsconfig.e2e.json
  projects/aca-shared/tsconfig.lib.json
  projects/aca-shared/tsconfig.spec.json
  projects/aca-testing-shared/tsconfig.lib.json
  projects/adf-office-services-ext/tsconfig.lib.json
  projects/adf-office-services-ext/tsconfig.spec.json
  scripts/run
  src/tsconfig.app.json
  src/tsconfig.spec.json
  tsconfig.base.json
  tsconfig.json
Labels: PR: unreviewed

#1595 LOC-244 - ACA files fully updated in 16 languages
  src/assets/i18n/ar.json
  src/assets/i18n/cs.json
  src/assets/i18n/da.json
  src/assets/i18n/de.json
  src/assets/i18n/es.json
  src/assets/i18n/fi.json
  src/assets/i18n/fr.json
  src/assets/i18n/it.json
  src/assets/i18n/ja.json
  src/assets/i18n/nb.json
  src/assets/i18n/nl.json
  src/assets/i18n/pl.json
  src/assets/i18n/pt-BR.json
  src/assets/i18n/ru.json
  src/assets/i18n/sv.json
  src/assets/i18n/zh-CN.json
Labels: PR: partially-approved

#1597 Fixed sorting for filters
  src/app.config.json
  src/app/components/files/files.component.html
  src/app/components/page.component.ts
Labels: PR: unreviewed

#1600 [ACA-3848] - change default file sorting
  e2e/protractor.excludes.json
  e2e/suites/list-views/personal-files.test.ts
  src/app/components/files/files.component.html
Labels: PR: reviewed-approved

#1602 [AAE-3278] Temporary fix for some flakyness: C297638 and C297638
  .travis.yml
  protractor.conf.js
  scripts/ci/job_hooks/after_e2e.sh
  scripts/ci/job_hooks/before_e2e.sh
  scripts/ci/job_hooks/before_install.sh
  scripts/npm/lite-serve.ts
  scripts/run
Labels: PR: reviewed-approved

#1599 [ACA-3830] Fix favorites navigation
  karma.conf.js
  package-lock.json
  package.json
  projects/aca-shared/karma.conf.js
  projects/adf-office-services-ext/karma.conf.js
  src/app/components/files/files.component.spec.ts
  src/app/components/files/files.component.ts
  src/app/components/shared-files/shared-files.component.spec.ts
  src/app/testing/app-testing.module.ts
Labels: PR: reviewed-approved

#1601 [ACA-3506] - added refresh for filters
  src/app/components/files/files.component.html
  src/app/components/files/files.component.spec.ts
  src/app/components/files/files.component.ts
Labels: PR: unreviewed

#1605 [ACA-3852] Document List - sort doesn't work
  src/app/components/favorites/favorites.component.html
  src/app/components/recent-files/recent-files.component.html
  src/app/components/shared-files/shared-files.component.html
  src/app/components/trashcan/trashcan.component.html
Labels: PR: reviewed-approved

#1606 Update protractor.conf.js
  e2e/e2e-config/hooks/after-launch.js
  package-lock.json
  package.json
  protractor.conf.js
Labels: PR: partially-approved

#1607 [ACA-3855] fix go home id you are in uuuid root
  src/app/components/files/files.component.spec.ts
  src/app/components/files/files.component.ts
Labels: PR: unreviewed

#1608 [ACA-3852] fix client sorting issues
  src/app/components/favorite-libraries/favorite-libraries.component.html
  src/app/components/libraries/libraries.component.html
Labels: PR: reviewed-approved

#1609 fix commonjs warnings for angular cli
  angular.json
Labels: PR: reviewed-approved

#1614 Remove excluded test
  e2e/protractor.excludes.json
Labels: PR: reviewed-approved

#1616 stabilize the node selector tests
  src/app/services/node-actions.service.spec.ts
Labels: PR: reviewed-approved

#1615 [ACA-3857]Fix config for search-headers
  src/app.config.json
Labels: PR: partially-approved

#1617 [ACA-3542] Fix Filter Sorting Initialization
  src/app/components/page.component.ts
Labels: PR: partially-approved

#1624 Release 2.0.0
  docs/audit/audit-info-2.0.0.md
  docs/licences/license-info-2.0.0.md
  package-lock.json
  package.json
  projects/aca-shared/package.json
  projects/aca-testing-shared/package.json
  projects/adf-office-services-ext/package.json
  src/app/components/favorites/favorites.component.spec.ts
  src/app/components/recent-files/recent-files.component.spec.ts
  src/app/components/shared-files/shared-files.component.spec.ts
  src/app/components/sidenav/sidenav.component.spec.ts
Labels: PR: unreviewed

#1634 [ACA-3730] - Fix create menu and viewer evaluators not in sync with store values
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.ts
  src/app/components/create-menu/create-menu.component.ts
  src/app/components/viewer/viewer.component.ts
Labels: PR: partially-approved
