Repository Alfresco/alfresco-content-app, pull requests merged in 2020-10, with the labels that each got.

#1702 Update to latest ADF and fix unit tests and broken e2e
  e2e/suites/search/search-filters.test.ts
  package-lock.json
  package.json
  projects/aca-shared/src/lib/services/app.service.spec.ts
Labels: PR: partially-approved

#1705 cleanup docker files
  docker-compose.e2e.yml
  docker-compose.yml
  docker/Readme.md
  docker/acs-cm/Readme.md
  docker/acs-cm/acme-bootstrap-context.xml
  docker/acs-cm/acme-content-model.xml
  docker/auth/alfresco-realm.json
  docker/proxy/nginx.conf
  package-lock.json
  package.json
  sanity-check.sh
  start.sh
Labels: PR: partially-approved

#1706 Megabump
  package-lock.json
  package.json
Labels: PR: partially-approved

#1713 extra unit tests
  projects/aca-shared/rules/src/app.rules.spec.ts
  projects/aca-shared/rules/src/test-rule-context.ts
  src/app/components/context-menu/context-menu.component.spec.ts
Labels: PR: unreviewed

#1714 [ACA-4025] - fix for silent refresh
  src/app.config.json
Labels: PR: partially-approved

#1720 add "create menu" unit tests
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.html
  src/app/components/create-menu/create-menu.component.spec.ts
Labels: PR: unreviewed

#1719 [ACA-4022] Remove custom redirect strategy, the viewer doesn not reload
  projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.spec.ts
  projects/aca-shared/src/lib/adf-extensions/extensions-data-loader.guard.ts
  projects/aca-shared/src/lib/routing/app.routes.strategy.spec.ts
  projects/aca-shared/src/lib/routing/app.routes.strategy.ts
  projects/aca-shared/src/lib/services/app.service.spec.ts
  projects/aca-shared/src/lib/services/app.service.ts
  projects/aca-shared/src/public-api.ts
  src/app/app.module.ts
Labels: PR: unreviewed

#1721 [ACA-3996] Libraries list is not re-ordered in ACA as it is in ADW
  e2e/suites/actions-available/special-permissions/other-permissions.ts
  e2e/suites/info-drawer/library-properties.test.ts
  e2e/suites/navigation/breadcrumb.test.ts
  e2e/suites/navigation/sidebar.test.ts
  src/assets/app.extensions.json
Labels: PR: unreviewed

#1728 e2e improvements part2
  .travis.yml
  e2e/suites/actions-available/files-folders/files-folders-actions.test.ts
  e2e/suites/actions-available/libraries/library.test.ts
  e2e/suites/actions/copy-move/copy.test.ts
  e2e/suites/actions/copy-move/move.test.ts
  e2e/suites/actions/delete-undo-delete.test.ts
  e2e/suites/actions/download.test.ts
  e2e/suites/actions/library-actions.test.ts
  e2e/suites/actions/permanently-delete.test.ts
  e2e/suites/actions/restore.test.ts
  e2e/suites/actions/share-file.test.ts
  e2e/suites/actions/unshare-file-search-results.test.ts
  e2e/suites/actions/unshare-file.test.ts
  e2e/suites/info-drawer/comments.test.ts
  e2e/suites/list-views/favorites.test.ts
  e2e/suites/list-views/generic-errors.test.ts
  e2e/suites/list-views/permissions.test.ts
  e2e/suites/list-views/recent-files.test.ts
  e2e/suites/list-views/shared-files.test.ts
  e2e/suites/list-views/tooltips.test.ts
  e2e/suites/list-views/trash.test.ts
  e2e/suites/navigation/single-click.test.ts
  e2e/suites/pagination/multiple-pages-trash.test.ts
  e2e/suites/pagination/single-page.test.ts
  e2e/suites/viewer/viewer-actions.test.ts
  e2e/suites/viewer/viewer-general.test.ts
  projects/aca-testing-shared/src/utilities/admin-actions.ts
  projects/aca-testing-shared/src/utilities/index.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/comments/comments-api.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/index.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/nodes/nodes-api.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/sites/sites-api.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/trashcan/trashcan-api.ts
  projects/aca-testing-shared/src/utilities/repo-client/repo-client.ts
  projects/aca-testing-shared/src/utilities/user-actions.ts
Labels: PR: partially-approved

#1732 [ACA-2314] display "locked by" in search results
  projects/aca-shared/src/lib/components/locked-by/locked-by.component.scss
  projects/aca-shared/src/lib/components/locked-by/locked-by.component.ts
  projects/aca-shared/src/lib/components/locked-by/locked-by.module.ts
  src/app/components/dl-custom-components/name-column/name-column.component.html
  src/app/components/dl-custom-components/name-column/name-column.component.ts
  src/app/components/search/search-results-row/search-results-row.component.html
  src/app/components/search/search-results-row/search-results-row.component.ts
  src/app/components/search/search-results.module.ts
  src/assets/i18n/en.json
Labels: PR: partially-approved

#1739 [ACA-4045] Show Document List header if filter header is active
  src/app/components/files/files.component.html
  src/app/components/files/files.component.spec.ts
  src/app/components/files/files.component.ts
  src/app/testing/translation.service.ts
  src/assets/i18n/en.json
Labels: PR: reviewed-approved

#1738 [ACA-4041] [ADW] Sort order doesn't work correctly after opening a document
  src/app/components/files/files.component.spec.ts
  src/app/components/files/files.component.ts
  src/app/components/viewer/viewer.component.ts
Labels: PR: partially-approved

#1741 improve update version script
  scripts/update-version.sh
Labels: PR: reviewed-approved

#1730 [ADF-5247] always enabled language picker (via extensions)
  docs/extending/rules.md
  docs/getting-started/internationalization.md
  docs/images/aca-i18n-02.png
  docs/ja/getting-started/internationalization.md
  e2e/suites/authentication/logout.test.ts
  projects/aca-shared/rules/src/app.rules.spec.ts
  projects/aca-shared/rules/src/app.rules.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  projects/aca-shared/src/lib/testing/lib-testing-module.ts
  projects/aca-shared/store/src/selectors/app.selectors.ts
  projects/aca-shared/store/src/states/app.state.ts
  projects/aca-testing-shared/src/components/header/header.ts
  projects/aca-testing-shared/src/pages/browsing-page.ts
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/components/common/language-picker/language-picker.component.ts
  src/app/components/common/logout/logout.component.ts
  src/app/components/current-user/current-user.component.spec.ts
  src/app/components/current-user/current-user.component.ts
  src/app/extensions/core.extensions.module.ts
  src/app/store/initial-state.ts
  src/app/store/reducers/app.reducer.ts
  src/assets/app.extensions.json
  src/assets/plugins/app.create.json
  src/assets/plugins/app.header.json
Labels: PR: partially-approved

#1746 [ADF-5249] about and package fixes
  package-lock.json
  package.json
  projects/aca-about/src/lib/about.component.ts
Labels: PR: partially-approved

#1747 deprecate NPM publishing
  .gitmodules
  .travis.yml
  package.json
  scripts/travis/release/release-npm.sh
Labels: PR: partially-approved

#1762 [ACA-4100] use ADF user info component
  e2e/suites/authentication/login.test.ts
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  src/app/app.module.ts
  src/app/components/current-user/current-user.component.html
  src/app/components/current-user/current-user.component.spec.ts
  src/app/components/current-user/current-user.component.theme.scss
  src/app/components/current-user/current-user.component.ts
  src/app/components/current-user/current-user.module.ts
  src/app/components/current-user/user-menu-item.component.html
  src/app/components/current-user/user-menu-item.component.spec.ts
  src/app/components/current-user/user-menu-item.component.ts
  src/app/components/header/header.module.ts
  src/app/extensions/core.extensions.module.ts
  src/app/ui/custom-theme.scss
Labels: PR: unreviewed

#1764 Styles cleanup
  projects/aca-shared/src/lib/components/tool-bar/toolbar-action/toolbar-action.component.scss
  projects/aca-shared/src/lib/components/tool-bar/toolbar-action/toolbar-action.component.ts
  projects/aca-shared/store/src/effects/snackbar.effects.ts
  src/app/components/context-menu/context-menu.component.theme.scss
  src/app/components/context-menu/context-menu.component.ts
  src/app/components/dl-custom-components/name-column/name-column.component.scss
  src/app/components/dl-custom-components/name-column/name-column.component.ts
  src/app/components/header/header.component.scss
  src/app/components/layout/app-layout/app-layout.component.scss
  src/app/components/layout/app-layout/app-layout.component.ts
  src/app/components/layout/app-layout/app-layout.theme.scss
  src/app/components/layout/layout.theme.scss
  src/app/components/permissions/permission-manager/permission-manager.component.scss
  src/app/components/permissions/permission-manager/permission-manager.component.theme.scss
  src/app/components/permissions/permission-manager/permission-manager.component.ts
  src/app/components/search/search-results-row/search-results-row.component.scss
  src/app/components/toolbar/toolbar-action/toolbar-actions.component.scss
  src/app/dialogs/node-versions/node-versions.dialog.html
  src/app/dialogs/node-versions/node-versions.dialog.scss
  src/app/dialogs/node-versions/node-versions.dialog.theme.scss
  src/app/dialogs/node-versions/node-versions.dialog.ts
  src/app/ui/custom-theme.scss
  src/app/ui/overrides/adf-style-fixes.theme.scss
  src/app/ui/snackbar.scss
Labels: PR: unreviewed
