Repository Alfresco/alfresco-content-app, pull requests merged in 2020-11, with the labels that each got.

#1772 Remove rancher update
  .travis.yml
  scripts/travis/deploy/publish.sh
  scripts/travis/deploy/rancher-update.sh
Labels: PR: reviewed-approved

#1742 app/config.json Replace values instead of override
  scripts/app-config-replace.js
Labels: PR: partially-approved

#1750 [ADF-5252] Disable settings and about pages by default
  docs/extending/README.md
  docs/extending/extending.md
  docs/extending/settings.md
  projects/aca-about/README.md
  projects/aca-settings/README.md
  projects/aca-settings/assets/aca-settings-custom-group.png
  src/app/extensions.module.ts
  src/assets/app.extensions.json
  src/assets/plugins/app.about.json
  src/assets/plugins/app.settings.json
Labels: PR: partially-approved

#1790 [ACS-827] - Added check for exclude error redirect to login for some …
  package-lock.json
  package.json
  src/app/app.component.ts
Labels: PR: unreviewed

#1803 [ACA-4026] Register plugins dynamically
  package-lock.json
  package.json
  projects/adf-office-services-ext/src/lib/aos-extension.module.ts
  src/assets/app.extensions.json
Labels: PR: unreviewed

#1799 [ACA-4143] support ordering of document list columns
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  src/assets/app.extensions.json
Labels: PR: reviewed-approved

#1812 increase default timeout due possible slow env
  .travis.yml
  e2e/protractor.excludes.json
  e2e/suites/actions-available/files-folders/favorites.ts
  e2e/suites/actions-available/files-folders/files-folders-actions.test.ts
  e2e/suites/actions-available/files-folders/folders-actions.test.ts
  e2e/suites/actions-available/files-folders/locked-files-actions.test.ts
  e2e/suites/actions-available/files-folders/multiple-files-actions.test.ts
  e2e/suites/actions-available/files-folders/office-files-actions.test.ts
  e2e/suites/actions-available/files-folders/personal-files.ts
  e2e/suites/actions-available/files-folders/recent-files.ts
  e2e/suites/actions-available/files-folders/search-results.ts
  e2e/suites/actions-available/files-folders/shared-files.ts
  e2e/suites/actions-available/files-folders/single-file-actions.test.ts
  e2e/suites/actions-available/files-folders/test-data.ts
  e2e/suites/actions-available/files-folders/trash.test.ts
  e2e/suites/actions-available/files-folders/trash.ts
  e2e/suites/actions-available/files-folders/viewer.ts
  e2e/suites/actions-available/libraries/library-trash.test.ts
  e2e/suites/actions-available/libraries/library.test.ts
  e2e/suites/actions-available/special-permissions/special-permissions-actions.test.ts
  e2e/suites/actions/delete-undo-delete.test.ts
  e2e/suites/actions/library-actions.test.ts
  e2e/suites/actions/share-file.test.ts
  e2e/suites/pagination/multiple-pages-files.test.ts
  e2e/suites/pagination/multiple-pages-libraries.test.ts
  e2e/suites/pagination/multiple-pages-trash.test.ts
  package.json
  projects/aca-testing-shared/src/components/data-table/data-table.ts
  projects/aca-testing-shared/src/components/search/search-input.ts
  projects/aca-testing-shared/src/pages/page.ts
  protractor.conf.js
Labels: PR: unreviewed

#1801 [ACA-3729] Join library action for Admin Users
  projects/aca-shared/rules/src/app.rules.ts
  projects/aca-shared/store/src/actions/library.actions.ts
  src/app/app.component.ts
  src/app/components/toolbar/toggle-join-library/toggle-join-library-button.component.ts
  src/app/components/toolbar/toggle-join-library/toggle-join-library.component.spec.ts
  src/app/directives/library-membership.directive.spec.ts
  src/app/directives/library-membership.directive.ts
  src/app/store/effects/library.effects.ts
Labels: PR: unreviewed

#1800 [ACS-880] Enable digital-work-space to join link to site with workspace template
  src/app/directives/library-membership.directive.spec.ts
  src/app/directives/library-membership.directive.ts
Labels: PR: unreviewed

#1815 add back try-catch around api calls
  e2e/e2e-config/utils/upload-output.js
  e2e/protractor.excludes.json
  e2e/suites/actions-available/libraries/library.test.ts
  e2e/suites/actions/create-file-from-template.test.ts
  e2e/suites/actions/create-folder-from-template.test.ts
  e2e/suites/actions/library-actions.test.ts
  e2e/suites/info-drawer/file-folder-properties.test.ts
  e2e/suites/list-views/empty-list.test.ts
  e2e/suites/list-views/favorites.test.ts
  e2e/suites/list-views/permissions.test.ts
  e2e/suites/pagination/multiple-pages-files.test.ts
  e2e/suites/pagination/recent-files.ts
  e2e/suites/pagination/search-results.ts
  e2e/suites/pagination/shared-files.ts
  e2e/suites/viewer/viewer-actions.test.ts
  projects/aca-testing-shared/src/components/dialog/share-dialog.ts
  projects/aca-testing-shared/src/utilities/admin-actions.ts
  projects/aca-testing-shared/src/utilities/user-actions.ts
Labels: PR: unreviewed

#1789 [ACA-3601] Enable tests excluded by ACA-3601
  e2e/protractor.excludes.json
  protractor.conf.js
Labels: PR: unreviewed

#1816 [ACA-4168] - reset pagination on breadcrumb navigation
  package-lock.json
  package.json
  src/app/components/files/files.component.ts
Labels: PR: unreviewed
