Repository Alfresco/alfresco-content-app, pull requests merged in 2021-04, with the labels that each got.

#2072 Update branch for ADF 32043 and JS-API ^4.4.0-3338
  package-lock.json
  package.json
  src/app/components/dl-custom-components/name-column/name-column.component.spec.ts
Labels: PR: partially-approved

#2082 Update branch for ADF 32124 and JS-API 4.4.0-3364
  package-lock.json
  package.json
Labels: PR: partially-approved

#2081 [ACA-4355][ADW] The Process Management section becomes invisible on logout
  extension.schema.json
  src/app/components/sidenav/sidenav.component.html
  src/app/components/sidenav/sidenav.component.ts
Labels: PR: reviewed-changes-requested

#2083 [ACA-4374] FE - [ADW] Navigate to Smart Folder subfolders throws "This item no longer exists or you don't have permission to view it."
  src/app/components/files/files.component.spec.ts
  src/app/components/files/files.component.ts
Labels: PR: partially-approved

#2086 [ACA-4383] - Fix pagination when performing navigation
  src/app/components/files/files.component.spec.ts
  src/app/components/files/files.component.ts
Labels: PR: unreviewed

#2085 Update branch for ADF 32159 and JS-API 4.4.0-3371
  package-lock.json
  package.json
Labels: PR: partially-approved

#2074 [ACA-2078] fix Flickering viewer toolbar icons when navigating to next/previous …
  src/app/components/viewer/viewer.component.ts
Labels: PR: unreviewed

#2006 [ACA-4288] Fix API errors from logs
  e2e/suites/actions-available/files-folders/folders-actions.test.ts
  e2e/suites/actions-available/files-folders/locked-files-actions.test.ts
  e2e/suites/actions-available/files-folders/multiple-files-actions.test.ts
  e2e/suites/actions-available/files-folders/office-files-actions.test.ts
  e2e/suites/actions-available/files-folders/single-file-actions.test.ts
  e2e/suites/actions-available/files-folders/trash.test.ts
  e2e/suites/actions-available/libraries/library-trash.test.ts
  e2e/suites/actions-available/libraries/library.test.ts
  e2e/suites/actions/copy-move/copy.test.ts
  e2e/suites/actions/copy-move/destination-picker-dialog.test.ts
  e2e/suites/actions/copy-move/move.test.ts
  e2e/suites/actions/create/create-file-from-template.test.ts
  e2e/suites/actions/create/create-folder-from-template.test.ts
  e2e/suites/actions/delete/delete-undo-delete.test.ts
  e2e/suites/actions/delete/permanently-delete.test.ts
  e2e/suites/actions/delete/restore.test.ts
  e2e/suites/actions/edit/edit-folder.test.ts
  e2e/suites/actions/favorite/mark-favorite.test.ts
  e2e/suites/actions/library/library-actions.test.ts
  e2e/suites/actions/share/share-file.test.ts
  e2e/suites/actions/share/unshare-file-search-results.test.ts
  e2e/suites/actions/share/unshare-file.test.ts
  e2e/suites/actions/upload-download/download.test.ts
  e2e/suites/application/general.test.ts
  e2e/suites/info-drawer/comments.test.ts
  e2e/suites/list-views/favorites.test.ts
  e2e/suites/list-views/file-libraries.test.ts
  e2e/suites/list-views/generic-errors.test.ts
  e2e/suites/list-views/permissions.test.ts
  e2e/suites/list-views/recent-files.test.ts
  e2e/suites/list-views/shared-files.test.ts
  e2e/suites/list-views/tooltips.test.ts
  e2e/suites/list-views/trash.test.ts
  e2e/suites/navigation/single-click.test.ts
  e2e/suites/pagination/multiple-pages-libraries.test.ts
  e2e/suites/pagination/multiple-pages-trash.test.ts
  e2e/suites/pagination/single-page.test.ts
  e2e/suites/search/search-results-libraries.test.ts
  e2e/suites/viewer/viewer-actions.test.ts
  e2e/suites/viewer/viewer-general.test.ts
  projects/aca-testing-shared/src/components/data-table/data-table.ts
  projects/aca-testing-shared/src/components/dialog/generic-dialog.ts
  projects/aca-testing-shared/src/components/menu/menu.ts
  projects/aca-testing-shared/src/components/sidenav/sidenav.ts
  projects/aca-testing-shared/src/pages/login-page.ts
  projects/aca-testing-shared/src/pages/page.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/shared-links/shared-links-api.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/sites/sites-api.ts
  projects/aca-testing-shared/src/utilities/utils.ts
Labels: PR: unreviewed

#2087 Update branch for ADF 32181 and JS-API 4.4.0-3371
  package-lock.json
  package.json
Labels: PR: partially-approved

#2093 Run the unit/build/e2e/docker based on the agreed doc
  .travis.yml
  scripts/travis/deploy/publish.sh
Labels: PR: partially-approved

#2091 [ACA-3908] use different selectors that are valid for ADW as well
  e2e/suites/actions/library/library-actions.test.ts
  projects/aca-testing-shared/src/components/dialog/create-edit-folder-dialog.ts
  projects/aca-testing-shared/src/components/dialog/create-from-template-dialog.ts
  projects/aca-testing-shared/src/components/dialog/create-library-dialog.ts
  projects/aca-testing-shared/src/components/search/filters/facet-filter.ts
  protractor.conf.js
Labels: PR: partially-approved

#2080 [ACA-4365] Expanded info drawer for permissions, properties and comments
  e2e/resources/extensibility-configs/context-submenus-ext.json
  e2e/resources/extensibility-configs/document-presets-ext.json
  e2e/resources/extensibility-configs/header-ext.json
  e2e/resources/extensibility-configs/info-drawer-ext.json
  e2e/resources/extensibility-configs/info-drawer-no-tabs-ext.json
  e2e/resources/extensibility-configs/metadata-ext.json
  e2e/resources/extensibility-configs/viewer-ext.json
  package-lock.json
  package.json
  projects/aca-shared/store/src/actions/node.actions.ts
  projects/aca-shared/store/src/actions/router.actions.ts
  projects/aca-shared/store/src/effects/router.effects.ts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/components/details/details.component.html
  src/app/components/details/details.component.scss
  src/app/components/details/details.component.spec.ts
  src/app/components/details/details.component.ts
  src/app/components/info-drawer/comments-tab/comments-tab.component.ts
  src/app/components/info-drawer/info.drawer.module.ts
  src/app/components/info-drawer/library-metadata-tab/library-metadata-tab.component.ts
  src/app/components/permissions/permission-dialog/node-permissions.dialog.html
  src/app/components/permissions/permission-dialog/node-permissions.dialog.spec.ts
  src/app/components/permissions/permission-dialog/node-permissions.dialog.ts
  src/app/components/permissions/permission-manager/permission-manager.component.html
  src/app/components/permissions/permission-manager/permission-manager.component.scss
  src/app/components/permissions/permission-manager/permission-manager.component.spec.ts
  src/app/components/permissions/permission-manager/permission-manager.component.ts
  src/app/components/permissions/permissions.module.ts
  src/app/services/content-management.service.ts
  src/app/store/effects/node.effects.spec.ts
  src/app/store/effects/node.effects.ts
  src/app/ui/custom-theme.scss
  src/assets/app.extensions.json
  src/assets/i18n/en.json
Labels: PR: partially-approved

#2094 Refactor env variables
  .travis.yml
  .travis/env.yml
  package.json
  protractor.conf.js
  scripts/app-config-replace.js
  scripts/ci/job_hooks/after_e2e.sh
  scripts/ci/job_hooks/before_e2e.sh
  scripts/npm/helpers/project-selectors.ts
  scripts/npm/lite-serve.ts
  src/proxy.conf.js
Labels: PR: partially-approved

#2052 [ACA-4287] Move hooks to shared library
  docs/extending/README.md
  docs/extending/application-hook.md
  projects/aca-settings/src/lib/settings.component.spec.ts
  projects/aca-shared/src/lib/directives/pagination.directive.spec.ts
  projects/aca-shared/src/lib/services/app-hook.service.ts
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/router.extension.service.spec.ts
  projects/aca-shared/src/lib/testing/lib-testing-module.ts
  projects/aca-shared/src/public-api.ts
  projects/aca-shared/store/src/actions/library.actions.ts
  src/app/components/favorite-libraries/favorite-libraries.component.spec.ts
  src/app/components/favorite-libraries/favorite-libraries.component.ts
  src/app/components/libraries/libraries.component.ts
  src/app/components/preview/preview.component.spec.ts
  src/app/components/preview/preview.component.ts
  src/app/components/search/search-input/search-input.component.spec.ts
  src/app/components/search/search-input/search-input.component.ts
  src/app/components/search/search-libraries-results/search-libraries-results.component.ts
  src/app/components/shared-files/shared-files.component.ts
  src/app/components/toolbar/toggle-favorite-library/toggle-favorite-library.component.spec.ts
  src/app/components/toolbar/toggle-favorite-library/toggle-favorite-library.component.ts
  src/app/components/toolbar/toggle-join-library/toggle-join-library-button.component.ts
  src/app/components/toolbar/toggle-join-library/toggle-join-library-menu.component.ts
  src/app/components/toolbar/toggle-join-library/toggle-join-library.component.spec.ts
  src/app/components/viewer/viewer.component.ts
  src/app/directives/document-list.directive.spec.ts
  src/app/directives/document-list.directive.ts
  src/app/services/content-management.service.spec.ts
  src/app/services/content-management.service.ts
  src/app/store/effects/app.effects.ts
  src/app/store/effects/library.effects.ts
  src/app/store/effects/template.effects.spec.ts
  src/app/store/effects/template.effects.ts
Labels: PR: partially-approved

#2098 [SEARCH-2590] Exclude tests
  e2e/protractor.excludes.json
Labels: PR: partially-approved

#2096 [ACS-1524] Remove environment scan
  scripts/ci/job_hooks/after_e2e.sh
  scripts/ci/job_hooks/before_e2e.sh
Labels: PR: unreviewed

#2100 audit fixes
  package-lock.json
Labels: PR: reviewed-approved
