Repository Alfresco/alfresco-content-app, pull requests merged in 2021-03, with the labels that each got.

#2038 [ACA-4196] [ACA-4219] [ACA-4283] Delete some tests and reinclude some others
  e2e/protractor.excludes.json
  e2e/suites/actions/create/create-file-from-template.test.ts
  e2e/suites/actions/edit/edit-offline.test.ts
Labels: PR: partially-approved

#2037 [ACA-4320] Correctly trigger linksUnshared event after unsharing a file
  src/app/services/content-management.service.spec.ts
  src/app/services/content-management.service.ts
Labels: PR: partially-approved

#2041 [ACA-4323] Can't add aspects to a folder in ACA/ADW
  src/app/store/effects/node.effects.spec.ts
  src/app/store/effects/node.effects.ts
Labels: PR: partially-approved

#2048 Update adf 31741 and js api 4.3.0
  package-lock.json
  package.json
Labels: PR: unreviewed

#2049 Update branch for ADF 31752 and JS-API 4.3.0
  package-lock.json
  package.json
Labels: PR: partially-approved

#2053 ACA 2.3.0 with ADF 4.3.0
  docs/audit/audit-info-2.3.0.md
  docs/licences/license-info-2.3.0.md
  package-lock.json
  package.json
  projects/aca-about/package.json
  projects/aca-settings/package.json
  projects/aca-shared/package.json
  projects/aca-testing-shared/package.json
  projects/adf-office-services-ext/package.json
  src/app.config.json
Labels: PR: reviewed-approved

#2054 Update branch for ADF 31786 and JS-API 4.3.0
  package-lock.json
  package.json
Labels: PR: partially-approved

#2046 [ACA-4339] Libraries - Delete action for non-site members is rendered
  e2e/suites/actions-available/libraries/test-data-libraries.ts
  src/assets/app.extensions.json
Labels: PR: partially-approved

#2068 switch to ADF directives for libraries
  package-lock.json
  package.json
  src/app/components/toolbar/toggle-favorite-library/toggle-favorite-library.component.spec.ts
  src/app/components/toolbar/toggle-favorite-library/toggle-favorite-library.component.ts
  src/app/components/toolbar/toggle-join-library/toggle-join-library-button.component.ts
  src/app/components/toolbar/toggle-join-library/toggle-join-library-menu.component.ts
  src/app/components/toolbar/toggle-join-library/toggle-join-library.component.spec.ts
  src/app/directives/directives.module.ts
  src/app/directives/library-favorite.directive.spec.ts
  src/app/directives/library-favorite.directive.ts
  src/app/directives/library-membership.directive.spec.ts
  src/app/directives/library-membership.directive.ts
Labels: PR: reviewed-approved

#2066 Update branch for ADF 31963 and JS-API 4.3.0
  package-lock.json
  package.json
Labels: PR: unreviewed
