Repository Alfresco/alfresco-content-app, pull requests merged in 2021-09, with the labels that each got.

#2276 Update branch for ADF 33296 and JS-API 4.6.0-3790 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2283 Update branch for ADF 33313 and JS-API 4.6.0-3790 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2275 [ACA-1918] Improve reload
  src/app/components/files/files.component.html
Labels: PR: unreviewed

#2281 [ACA-3669] Incorrect Version Number Displayed
  projects/aca-shared/src/lib/services/content-api.service.ts
  src/app/dialogs/node-versions/node-versions.dialog.html
  src/app/dialogs/node-versions/node-versions.dialog.spec.ts
  src/app/dialogs/node-versions/node-versions.dialog.ts
  src/app/services/content-management.service.spec.ts
  src/app/services/content-management.service.ts
Labels: PR: unreviewed, PR: partially-approved

#2287 Update branch for ADF 33326 and JS-API 4.6.0-3790 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2291 [ACA-4226] Fix rule enabling in extensions
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
Labels: PR: partially-approved

#2292 Viewer tutorial
  docs/abn-tree.yml
  docs/extending/extensibility-features.md
  docs/tutorials/README.md
  docs/tutorials/custom-viewer.md
Labels: PR: unreviewed

#2288 Update branch for ADF 33337 and JS-API 4.6.0-3790 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2300 Release 2.6.0
  docs/audit/audit-info-2.6.0.md
  docs/licences/license-info-2.6.0.md
  package-lock.json
  package.json
  projects/aca-about/package.json
  projects/aca-settings/package.json
  projects/aca-shared/package.json
  projects/aca-testing-shared/package.json
  projects/adf-office-services-ext/package.json
Labels: PR: unreviewed

#2296 [AAE-5874] Re-evaluate extension rules when context changes
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.spec.ts
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-button/toolbar-button.component.html
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.html
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  src/app/components/context-menu/context-menu.component.spec.ts
  src/app/components/context-menu/context-menu.component.ts
  src/app/components/create-menu/create-menu.component.spec.ts
  src/app/components/create-menu/create-menu.component.ts
  src/app/components/header/header.component.spec.ts
  src/app/components/header/header.component.ts
  src/app/components/page.component.ts
  src/app/components/preview/preview.component.ts
  src/app/components/shared-link-view/shared-link-view.component.spec.ts
  src/app/components/shared-link-view/shared-link-view.component.ts
  src/app/components/viewer/viewer.component.ts
Labels: PR: partially-approved

#2290 [ACA-4203] The width of the "Size" column is too small and the text gets truncated
  src/app/ui/custom-theme.scss
Labels: PR: partially-approved

#2301 Revert "[AAE-5874] Re-evaluate extension rules when context changes"
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.spec.ts
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-button/toolbar-button.component.html
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.html
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  src/app/components/context-menu/context-menu.component.spec.ts
  src/app/components/context-menu/context-menu.component.ts
  src/app/components/create-menu/create-menu.component.spec.ts
  src/app/components/create-menu/create-menu.component.ts
  src/app/components/header/header.component.spec.ts
  src/app/components/header/header.component.ts
  src/app/components/page.component.ts
  src/app/components/preview/preview.component.ts
  src/app/components/shared-link-view/shared-link-view.component.spec.ts
  src/app/components/shared-link-view/shared-link-view.component.ts
  src/app/components/viewer/viewer.component.ts
Labels: PR: unreviewed
