Repository Alfresco/alfresco-content-app, pull requests merged in 2021-08, with the labels that each got.

#2244 Update branch for ADF 33176 and JS-API 4.6.0-3694 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2251 [ADF-5429] Remove old compatibility layer
  .travis.yml
  package-lock.json
  package.json
  projects/aca-shared/src/lib/services/app.service.spec.ts
  projects/aca-shared/src/lib/services/content-api.service.ts
  src/app/components/info-drawer/library-metadata-tab/library-metadata-form.component.spec.ts
  src/app/components/info-drawer/library-metadata-tab/library-metadata-form.component.ts
  src/app/components/libraries/libraries.component.spec.ts
  src/app/components/search/search-libraries-results/search-libraries-query-builder.service.spec.ts
  src/app/components/search/search-libraries-results/search-libraries-query-builder.service.ts
  src/app/components/search/search-results/search-results.component.spec.ts
  src/app/components/shared-link-view/shared-link-view.component.spec.ts
  src/app/components/shared-link-view/shared-link-view.component.ts
  src/app/components/toolbar/toggle-edit-offline/toggle-edit-offline.component.ts
  src/app/components/toolbar/toggle-favorite-library/toggle-favorite-library.component.spec.ts
  src/app/components/toolbar/toggle-join-library/toggle-join-library.component.spec.ts
  src/app/components/trashcan/trashcan.component.spec.ts
  src/app/components/viewer/viewer.component.ts
  src/app/services/node-actions.service.spec.ts
  src/app/services/node-actions.service.ts
  src/app/services/node-template.service.spec.ts
  src/app/services/node-template.service.ts
  src/app/store/app-store.module.ts
  src/app/store/bootstrap-effect.ts
  src/app/store/effects/template.effects.spec.ts
  src/app/store/effects/template.effects.ts
Labels: PR: unreviewed

#2254 move share bootstrap
  projects/aca-shared/store/src/bootstrap-effect.ts
  projects/aca-shared/store/src/public-api.ts
  src/app/store/app-store.module.ts
Labels: PR: reviewed-approved

#2255 [AAE-5660] Reduce SCSS mixins and use CSS variables instead
  src/app/components/create-menu/create-menu.component.scss
  src/app/components/create-menu/create-menu.component.ts
  src/app/components/details/details.component.scss
  src/app/components/details/details.component.ts
  src/app/components/search/search-input/search-input.component.scss
  src/app/components/search/search-input/search-input.component.ts
  src/app/components/sidenav/sidenav.component.scss
  src/app/components/sidenav/sidenav.component.theme.scss
  src/app/dialogs/node-template/create-from-template.dialog.scss
  src/app/dialogs/node-template/create-from-template.dialog.ts
  src/app/ui/custom-theme.scss
Labels: PR: partially-approved

#2256 improve compatibility
  package-lock.json
  package.json
  projects/aca-shared/README.md
  projects/aca-shared/karma.conf.js
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.html
  projects/aca-shared/src/lib/components/tool-bar/toolbar-action/toolbar-action.component.html
  projects/aca-shared/src/lib/services/content-api.service.ts
  projects/aca-shared/store/src/bootstrap-effect.ts
  projects/aca-shared/store/src/public-api.ts
  projects/aca-shared/tsconfig.lib.prod.json
  src/app/components/common/toggle-shared/toggle-shared.component.html
  src/app/components/context-menu/context-menu-item.component.html
  src/app/components/context-menu/context-menu.component.html
  src/app/components/create-menu/create-menu.component.html
  src/app/components/details/details.component.html
  src/app/components/details/details.component.scss
  src/app/components/favorites/favorites.component.html
  src/app/components/header/header.component.html
  src/app/components/info-drawer/library-metadata-tab/library-metadata-form.component.ts
  src/app/components/search/search-action-menu/search-action-menu.component.html
  src/app/components/search/search-input-control/search-input-control.component.html
  src/app/components/search/search-input/search-input.component.html
  src/app/components/search/search-libraries-results/search-libraries-query-builder.service.ts
  src/app/components/search/search-libraries-results/search-libraries-results.component.html
  src/app/components/search/search-results/search-results.component.html
  src/app/components/shared-link-view/shared-link-view.component.html
  src/app/components/sidenav/components/expand-menu.component.html
  src/app/components/viewer/viewer.component.ts
  src/app/services/node-actions.service.ts
  src/app/services/node-template.service.ts
  src/app/store/app-store.module.ts
  src/app/store/effects/template.effects.ts
Labels: PR: unreviewed

#2271 Update branch for ADF 33282 and JS-API 4.6.0-3790 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2273 Update branch for ADF 33286 and JS-API 4.6.0-3790 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed
