Repository Alfresco/alfresco-content-app, pull requests merged in 2021-07, with the labels that each got.

#2208 fix e2e uploadOutput error
  e2e/e2e-config/utils/upload-output.js
Labels: PR: partially-approved

#2209 Update branch for ADF 32982 and JS-API 4.5.0-3650
  package-lock.json
  package.json
Labels: PR: partially-approved

#2207 [search-2897] test new search
  e2e/suites/actions-available/files-folders/folders-actions.test.ts
  e2e/suites/actions-available/special-permissions/search-results.ts
  e2e/suites/search/search-filters.test.ts
Labels: PR: partially-approved

#2210 search extension docs updates
  docs/extending/application-features.md
  docs/extending/extensibility-features.md
  extension.schema.json
  projects/aca-shared/src/lib/services/app.extension.service.ts
  src/assets/app.extensions.json
  src/assets/plugins/app.search.json
Labels: PR: unreviewed

#2211 Update branch for ADF 32991 and JS-API 4.5.0-3650
  package-lock.json
  package.json
Labels: PR: partially-approved

#2212 Update branch for ADF 32995 and JS-API 4.5.0-3650
  package-lock.json
  package.json
Labels: PR: partially-approved

#2216 Update branch for ADF 33001 and JS-API 4.5.0-3650
  package-lock.json
  package.json
Labels: PR: partially-approved

#2218 Fixed space between preview icon
  src/app/components/search/search-results/search-results.component.scss
Labels: PR: partially-approved

#2219 Update branch for ADF 33025 and JS-API 4.5.0-3650
  package-lock.json
  package.json
Labels: PR: partially-approved

#2225 Update branch for ADF 33045 and JS-API 4.5.0
  package-lock.json
  package.json
Labels: PR: partially-approved

#2224 [ACA-4506] - added 2 configurations for Dublin Core and Effectivity
  src/assets/app.extensions.json
  src/assets/i18n/en.json
Labels: PR: partially-approved

#2226 Fix retry screenshot
  protractor.conf.js
Labels: PR: reviewed-approved

#2217 LOC-318 - Updated files for ACA 2.3 in 16 languages
  src/assets/i18n/ar.json
  src/assets/i18n/cs.json
  src/assets/i18n/da.json
  src/assets/i18n/de.json
  src/assets/i18n/es.json
  src/assets/i18n/fi.json
  src/assets/i18n/fr.json
  src/assets/i18n/it.json
  src/assets/i18n/ja.json
  src/assets/i18n/nb.json
  src/assets/i18n/nl.json
  src/assets/i18n/pl.json
  src/assets/i18n/pt-BR.json
  src/assets/i18n/ru.json
  src/assets/i18n/sv.json
  src/assets/i18n/zh-CN.json
Labels: PR: unreviewed

#2227 [ACA-4507] Fix folder tests
  e2e/e2e-config/utils/upload-output.js
  e2e/suites/actions-available/files-folders/folders-actions.test.ts
  e2e/suites/actions-available/files-folders/locked-files-actions.test.ts
  e2e/suites/actions-available/files-folders/multiple-files-actions.test.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/search/search-api.ts
  protractor.conf.js
Labels: PR: unreviewed

#2228 v2.5.0
  docs/audit/audit-info-2.5.0.md
  docs/licences/license-info-2.5.0.md
  package-lock.json
  package.json
  projects/aca-about/package.json
  projects/aca-settings/package.json
  projects/aca-shared/package.json
  projects/aca-testing-shared/package.json
  projects/adf-office-services-ext/package.json
Labels: PR: reviewed-approved

#2190 [ACA-4492] - Start restyling of search sorting
  e2e/suites/search/search-sorting.test.ts
  projects/aca-testing-shared/src/components/search/search-sorting-picker.ts
  src/app/components/search/search-action-menu/search-action-menu.component.html
  src/app/components/search/search-action-menu/search-action-menu.component.spec.ts
  src/app/components/search/search-action-menu/search-action-menu.component.ts
  src/app/components/search/search-results.module.ts
  src/app/components/search/search-results/search-results.component.html
  src/app/components/search/search-results/search-results.component.ts
  src/assets/i18n/en.json
Labels: PR: partially-approved, next-version ➡️

#2229 Update branch for ADF 33051 and JS-API 4.5.0
  package-lock.json
  package.json
Labels: PR: partially-approved

#2234 Update branch for ADF 33076 and JS-API 4.5.0
  package-lock.json
  package.json
Labels: PR: partially-approved

#2223 [AAE-4585] Resolved - Disable actions that can not happen when naviga…
  src/app/components/files/files.component.ts
  src/app/components/page.component.spec.ts
  src/app/components/page.component.ts
Labels: PR: unreviewed

#2240 Update branch for ADF 33121 and JS-API 4.6.0-3694
  package-lock.json
  package.json
Labels: PR: unreviewed

#2241 Update branch for ADF 33140 and JS-API 4.6.0-3694
  package-lock.json
  package.json
Labels: PR: unreviewed

#2243 Update branch for ADF 33169 and JS-API 4.6.0-3694 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved
