Repository Alfresco/alfresco-content-app, pull requests merged in 2021-11, with the labels that each got.

#2332 Update branch for ADF 33686 and JS-API 4.7.0-3949 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2335 [MNT-22574] Support rules for search forms
  docs/tutorials/search-form.md
  extension.schema.json
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
Labels: PR: partially-approved

#2334 Update branch for ADF 33725 and JS-API 4.7.0-3949 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2339 [MNT-22574] Conditional AI Search
  docs/tutorials/search-form.md
  extension.schema.json
  package-lock.json
  package.json
  projects/aca-about/package.json
  projects/aca-settings/package.json
  projects/aca-shared/package.json
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  projects/aca-testing-shared/package.json
  projects/adf-office-services-ext/package.json
Labels: PR: partially-approved

#2341 Update branch for ADF 33742 and JS-API 4.7.0-3965 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2342 [ACS-2197] add changelog report generation
  docs/changelog/.gitkeep
  scripts/generate-reports.sh
Labels: PR: reviewed-approved

#2346 ACA-4526 Alfresco Content Application Docker Images are not available in Docker Hub from 2.3.0
  .travis.yml
  scripts/travis/deploy/publish.sh
Labels: PR: partially-approved

#2347 [ACA-4532] Flaky ACA unit test
  src/app/components/page.component.spec.ts
Labels: PR: partially-approved

#2352 Update branch for ADF 33821 and JS-API 4.7.0 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2360 [AAE-6309] Cleaning process references
  src/app/components/create-menu/create-menu.component.spec.ts
  src/app/components/main-action/main-action.component.html
  src/app/components/main-action/main-action.component.spec.ts
  src/app/components/main-action/main-action.component.ts
  src/app/testing/app-extension-service-mock.ts
  src/app/testing/content-action-ref.ts
Labels: PR: partially-approved

#2355 Update branch for ADF 33831 and JS-API 4.7.0 [ci:force]
  package-lock.json
  package.json
  src/app/testing/app-testing.module.ts
Labels: PR: unreviewed

#2362 Update branch for ADF 33875 and JS-API 4.8.0-3998 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2368 Update branch for ADF 33893 and JS-API 4.8.0-3998 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2361 [ACA-4382] Use adf about and make it available in prod mode
  .travis.yml
  projects/aca-about/src/lib/about.component.html
  projects/aca-about/src/lib/about.component.scss
  projects/aca-about/src/lib/about.component.spec.ts
  projects/aca-about/src/lib/about.component.ts
  projects/aca-about/src/lib/aca-about.module.ts
  projects/aca-about/src/lib/dev-mode.tokens.ts
  projects/aca-about/src/lib/extension-list/extension-list.component.html
  projects/aca-about/src/lib/extension-list/extension-list.component.ts
  projects/aca-about/src/lib/license-list/license-list.component.html
  projects/aca-about/src/lib/module-list/module-list.component.html
  projects/aca-about/src/lib/module-list/module-list.component.ts
  projects/aca-about/src/lib/package-list/package-list.component.html
  projects/aca-about/src/lib/package-list/package-list.component.ts
  projects/aca-about/src/lib/status-list/status-list.component.html
  projects/aca-about/src/lib/status-list/status-list.component.ts
  projects/aca-about/src/public-api.ts
  src/app/extensions.module.ts
Labels: PR: unreviewed
