Repository Alfresco/alfresco-content-app, pull requests merged in 2021-05, with the labels that each got.

#2095 [ACS-1519] - Fixed double loading of the viewer
  src/app/components/viewer/viewer.component.ts
Labels: PR: reviewed-approved

#2101 [ACA-3908] improve selector to be valid for ADW as well
  projects/aca-testing-shared/src/components/data-table/data-table.ts
Labels: PR: partially-approved

#2097 [ADF-5379] Add CropperJS dependency
  package-lock.json
  package.json
Labels: PR: partially-approved

#2099 [ADF-5378] Rotate image: auto increment version on submit
  angular.json
  package-lock.json
  package.json
  projects/aca-shared/store/src/actions/upload.actions.ts
  src/app/components/layout/app-layout/app-layout.component.scss
  src/app/components/viewer/viewer.component.html
  src/app/components/viewer/viewer.component.ts
  src/app/store/effects/upload.effects.spec.ts
  src/app/store/effects/upload.effects.ts
  src/assets/i18n/en.json
Labels: PR: partially-approved

#2102 Fix security issues and remove cpr dependency
  docs/extending/redistributable-libraries.md
  docs/ja/extending/redistributable-libraries.md
  docs/tutorials/how-to-create-your-first-extension.md
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#2103 Update branch for ADF 32383 and JS-API 4.4.0-3425
  package-lock.json
  package.json
Labels: PR: partially-approved

#2109 [ACA-3897] Extendable viewer navigation
  docs/extending/application-features.md
  extension.schema.json
  projects/aca-shared/src/lib/models/viewer.rules.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  src/app/components/viewer/viewer.component.ts
Labels: PR: partially-approved

#2108 Modify Japanese translation of building-from-source.md
  docs/ja/getting-started/building-from-source.md
Labels: PR: partially-approved

#2111 [ACA-3908] get Copy action by title to solve problem from ADW run
  projects/aca-testing-shared/src/components/component.ts
  projects/aca-testing-shared/src/components/menu/menu.ts
  projects/aca-testing-shared/src/components/toolbar/toolbar.ts
Labels: PR: partially-approved

#2112 Revert changes from dev-durse-ADF-5378-integration
  projects/aca-shared/store/src/actions/upload.actions.ts
  src/app/components/layout/app-layout/app-layout.component.scss
  src/app/components/viewer/viewer.component.html
  src/app/components/viewer/viewer.component.ts
  src/app/store/effects/upload.effects.spec.ts
  src/app/store/effects/upload.effects.ts
  src/assets/i18n/en.json
Labels: PR: partially-approved

#2113 Update branch for ADF 32421 and JS-API 4.4.0-3443
  package-lock.json
  package.json
Labels: PR: unreviewed

#2121 Modify Japanese translation for CORS docs.
  docs/ja/getting-started/cors.md
Labels: PR: partially-approved

#2120 Modify Japanese translation for Configuration docs.
  docs/ja/getting-started/configuration.md
Labels: PR: partially-approved

#2129 [ACA-4419] Exclude C326685 test
  e2e/protractor.excludes.json
  e2e/suites/actions-available/libraries/library.test.ts
Labels: PR: partially-approved

#2122 Update branch for ADF 32456 and JS-API 4.4.0-3449
  e2e/protractor.excludes.json
  package-lock.json
  package.json
Labels: PR: unreviewed

#2130 remove cropper
  package-lock.json
  package.json
Labels: PR: unreviewed

#2132 [ACA-4384] [ADW] Empty template or error template should be displayed in case error occurred when clicking a folder
  src/app/components/files/files.component.html
  src/app/components/files/files.component.spec.ts
  src/app/components/files/files.component.ts
Labels: PR: partially-approved

#2140 [ACA-4430] Add missing viewer routes for Viewing a previous version of a file in Libraries
  src/app/app.routes.ts
Labels: PR: partially-approved

#2137 [ACA-4339] Library actions - Delete
  e2e/suites/actions-available/libraries/test-data-libraries.ts
  src/assets/app.extensions.json
Labels: PR: partially-approved

#2139 Modify Japanese translation for Document List.
  docs/ja/features/document-list-layout.md
Labels: PR: partially-approved

#2135 Modify Japanese translation for SSO.
  docs/ja/getting-started/sso.md
Labels: PR: partially-approved

#2134 Modify Japanese translation for Navigation.
  docs/ja/getting-started/navigation.md
Labels: PR: partially-approved

#2133 Modify Japanese translation for Extending
  docs/ja/tutorials/how-to-create-your-first-extension.md
  docs/ja/tutorials/how-to-install-an-existing-extension.md
  docs/ja/tutorials/introduction-to-extending.md
Labels: PR: partially-approved

#2131 Modify Japanese translation for README
  docs/ja/README.md
Labels: PR: partially-approved

#2136 Update branch for ADF 32511 and JS-API 4.4.0-3493
  package-lock.json
  package.json
Labels: PR: partially-approved

#2138 [ACA-4432] Upload Dialog overlaps Upload New Version dialog
  e2e/suites/viewer/viewer-actions.test.ts
  projects/aca-testing-shared/src/components/viewer/viewer.ts
  src/app/components/layout/app-layout/app-layout.component.scss
Labels: PR: partially-approved

#2144 LOC-303 - Media strings for ACA in 16 languages
  src/assets/i18n/ar.json
  src/assets/i18n/cs.json
  src/assets/i18n/da.json
  src/assets/i18n/de.json
  src/assets/i18n/es.json
  src/assets/i18n/fi.json
  src/assets/i18n/fr.json
  src/assets/i18n/it.json
  src/assets/i18n/ja.json
  src/assets/i18n/nb.json
  src/assets/i18n/nl.json
  src/assets/i18n/pl.json
  src/assets/i18n/pt-BR.json
  src/assets/i18n/ru.json
  src/assets/i18n/sv.json
  src/assets/i18n/zh-CN.json
Labels: PR: partially-approved

#2141 Update branch for ADF 32545 and JS-API 4.4.0-3493
  package-lock.json
  package.json
Labels: PR: unreviewed

#2145 Update branch for ADF 32569 and JS-API 4.4.0-3493
  package-lock.json
  package.json
Labels: PR: partially-approved

#2146 [ADF-5391] Cannot update multi-value metadata property
  e2e/e2e-config/utils/build-number.js
  e2e/e2e-config/utils/upload-output.js
  projects/aca-shared/src/lib/services/app.extension.service.ts
  protractor.conf.js
  src/app.config.json
  src/app/components/info-drawer/metadata-tab/metadata-tab.component.spec.ts
  src/app/components/info-drawer/metadata-tab/metadata-tab.component.ts
Labels: PR: unreviewed

#2147 Update branch for ADF 32576 and JS-API 4.4.0-3493
  package-lock.json
  package.json
Labels: PR: unreviewed

#2148 [ACA-4445] - added condition to check major version 7
  projects/aca-shared/rules/src/app.rules.ts
  projects/aca-shared/rules/src/repository.rules.ts
Labels: PR: unreviewed

#2150 Update branch for ADF 32587 and JS-API 4.4.0-3493
  package-lock.json
  package.json
Labels: PR: partially-approved

#2151 2.4.0
  docs/audit/audit-info-2.4.0.md
  docs/licences/license-info-2.4.0.md
  package-lock.json
  package.json
  projects/aca-about/package.json
  projects/aca-settings/package.json
  projects/aca-shared/package.json
  projects/aca-testing-shared/package.json
  projects/adf-office-services-ext/package.json
  src/app.config.json
Labels: PR: reviewed-approved

#2156 [ACA-376] navigate inside original folder when clicking on a folder-link
  src/app/components/files/files.component.spec.ts
  src/app/components/files/files.component.ts
Labels: PR: partially-approved

#2149 [AAE-5145] Update node actions to use enum
  package-lock.json
  package.json
  src/app/services/node-actions.service.spec.ts
  src/app/services/node-actions.service.ts
  src/app/services/node-template.service.ts
Labels: PR: partially-approved
