Repository Alfresco/alfresco-content-app, pull requests merged in 2021-06, with the labels that each got.

#2152 Update branch for ADF 32602 and JS-API 4.4.0
  e2e/suites/extensions/ext-info-drawer.test.ts
  e2e/suites/extensions/ext-viewer.test.ts
  e2e/suites/navigation/breadcrumb.test.ts
  package-lock.json
  package.json
  projects/aca-testing-shared/src/components/info-drawer/info-drawer.ts
  projects/aca-testing-shared/src/pages/page.ts
Labels: PR: unreviewed

#2163 [ACS-1636] Make SideNav Create New Button steady
  src/app/components/sidenav/sidenav.component.html
  src/app/components/sidenav/sidenav.component.scss
Labels: PR: partially-approved

#2157 [ADF-5407] style fixes before Angular 12 upgrade
  projects/aca-about/src/lib/about.component.ts
  projects/aca-shared/src/lib/components/page-layout/page-layout.component.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-button/toolbar-button.component.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.ts
  src/app/components/context-menu/context-menu-item.component.ts
  src/app/components/create-menu/create-menu.component.ts
  src/app/components/details/details.component.html
  src/app/components/details/details.component.scss
  src/app/components/details/details.component.ts
  src/app/components/dl-custom-components/name-column/name-column.component.ts
  src/app/components/header/header.component.ts
  src/app/components/preview/preview.component.ts
  src/app/components/search/search-input/search-input.component.ts
  src/app/components/shared-link-view/shared-link-view.component.ts
  src/app/dialogs/node-template/create-from-template.dialog.ts
Labels: PR: unreviewed

#2166 Update branch for ADF 32755 and JS-API 4.5.0-3561
  package-lock.json
  package.json
Labels: PR: unreviewed

#2174 [ACA-3611] Add parentFolderId variable to getNodeByPath()
  projects/aca-testing-shared/src/utilities/repo-client/apis/favorites/favorites-api.ts
  projects/aca-testing-shared/src/utilities/repo-client/apis/nodes/nodes-api.ts
Labels: PR: partially-approved

#2179 Remove ora not used dependency
  package-lock.json
  package.json
  protractor.conf.js
Labels: PR: unreviewed

#2172 Update branch for ADF 32787 and JS-API 4.5.0-3561
  package-lock.json
  package.json
Labels: PR: unreviewed

#2180 Update branch for ADF 32857 and JS-API 4.5.0-3603
  package-lock.json
  package.json
Labels: PR: unreviewed

#2164 [ACA-3541] show error message on empty search
  src/app/components/search/search-input/search-input.component.spec.ts
  src/app/components/search/search-input/search-input.component.ts
  src/assets/i18n/en.json
Labels: PR: unreviewed

#2182 [ADF-5423] remove deprecated async from unit tests
  src/app/components/header/header.component.spec.ts
  src/app/services/node-actions.service.spec.ts
Labels: PR: reviewed-approved

#2169 [ACA-4471] - Added show preview action for files in search results
  projects/aca-shared/rules/src/app.rules.ts
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.html
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.ts
  projects/aca-shared/store/src/actions/app.actions.ts
  projects/aca-shared/store/src/selectors/app.selectors.ts
  projects/aca-shared/store/src/states/app.state.ts
  src/app/components/search/search-results/search-results.component.html
  src/app/components/search/search-results/search-results.component.scss
  src/app/components/search/search-results/search-results.component.ts
  src/app/components/toolbar/toggle-info-drawer/toggle-info-drawer.component.ts
  src/app/extensions/core.extensions.module.ts
  src/app/material.module.ts
  src/app/store/initial-state.ts
  src/app/store/reducers/app.reducer.ts
  src/assets/app.extensions.json
  src/assets/i18n/en.json
Labels: PR: partially-approved

#2188 Update to latest ADF testing usage
  package-lock.json
  package.json
Labels: PR: unreviewed

#2184 revert solution-style typescript configs
  e2e/tsconfig.e2e.json
  package-lock.json
  package.json
  projects/aca-about/tsconfig.lib.json
  projects/aca-about/tsconfig.spec.json
  projects/aca-settings/tsconfig.lib.json
  projects/aca-settings/tsconfig.spec.json
  projects/aca-shared/package.json
  projects/aca-shared/tsconfig.lib.json
  projects/aca-shared/tsconfig.spec.json
  projects/aca-testing-shared/package.json
  projects/aca-testing-shared/tsconfig.lib.json
  projects/adf-office-services-ext/package.json
  projects/adf-office-services-ext/tsconfig.lib.json
  projects/adf-office-services-ext/tsconfig.spec.json
  src/tsconfig.app.json
  src/tsconfig.spec.json
  tsconfig.base.json
  tsconfig.json
  tslint.json
Labels: PR: reviewed-approved

#2173 [ADF-5419][aca] support multiple search form
  e2e/suites/list-views/empty-list.test.ts
  src/app.config.json
  src/app/components/search/search-results/search-results.component.html
  src/app/components/search/search-results/search-results.component.scss
  src/app/components/search/search-results/search-results.component.spec.ts
  src/app/components/search/search-results/search-results.component.ts
  src/assets/i18n/en.json
Labels: PR: partially-approved

#2189 Update branch for ADF 32908 and JS-API 4.5.0-3603
  package-lock.json
  package.json
Labels: PR: unreviewed

#2194 Update branch for ADF 32926 and JS-API 4.5.0-3603
  package-lock.json
  package.json
Labels: PR: unreviewed

#2191 [ADF-5433] enable strict mode for angular templates
  projects/aca-settings/src/lib/settings.component.html
  projects/aca-settings/src/lib/settings.component.ts
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.html
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-action/toolbar-action.component.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-button/toolbar-button.component.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.html
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.html
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.ts
  src/app/components/context-menu/context-menu-item.component.html
  src/app/components/context-menu/context-menu-item.component.ts
  src/app/components/context-menu/context-menu.component.html
  src/app/components/context-menu/context-menu.component.ts
  src/app/components/context-menu/context-menu.service.ts
  src/app/components/create-menu/create-menu.component.html
  src/app/components/create-menu/create-menu.component.ts
  src/app/components/favorite-libraries/favorite-libraries.component.html
  src/app/components/favorite-libraries/favorite-libraries.component.ts
  src/app/components/favorites/favorites.component.html
  src/app/components/favorites/favorites.component.ts
  src/app/components/files/files.component.html
  src/app/components/files/files.component.spec.ts
  src/app/components/files/files.component.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/info-drawer/library-metadata-tab/library-metadata-form.component.html
  src/app/components/libraries/libraries.component.html
  src/app/components/libraries/libraries.component.ts
  src/app/components/page.component.ts
  src/app/components/preview/preview.component.html
  src/app/components/recent-files/recent-files.component.html
  src/app/components/recent-files/recent-files.component.ts
  src/app/components/search/search-libraries-results/search-libraries-results.component.html
  src/app/components/search/search-libraries-results/search-libraries-results.component.ts
  src/app/components/search/search-results-row/search-results-row.component.ts
  src/app/components/search/search-results/search-results.component.html
  src/app/components/search/search-results/search-results.component.ts
  src/app/components/shared-files/shared-files.component.html
  src/app/components/shared-files/shared-files.component.ts
  src/app/components/sidenav/components/button-menu.component.ts
  src/app/components/sidenav/components/expand-menu.component.ts
  src/app/components/sidenav/sidenav.component.html
  src/app/components/sidenav/sidenav.component.ts
  src/app/components/toolbar/toggle-info-drawer/toggle-info-drawer.component.ts
  src/app/components/trashcan/trashcan.component.html
  src/app/components/viewer/viewer.component.html
  src/app/components/viewer/viewer.component.ts
  src/app/dialogs/node-versions/node-versions.dialog.ts
  tsconfig.json
Labels: PR: unreviewed

#2195 [ACA-4487] support search forms layout
  docs/extending/application-actions.md
  docs/ja/extending/application-actions.md
  e2e/resources/extensibility-configs/context-submenus-ext.json
  e2e/resources/extensibility-configs/document-presets-ext.json
  e2e/resources/extensibility-configs/header-ext.json
  e2e/resources/extensibility-configs/info-drawer-ext.json
  e2e/resources/extensibility-configs/info-drawer-no-tabs-ext.json
  e2e/resources/extensibility-configs/metadata-ext.json
  e2e/resources/extensibility-configs/viewer-ext.json
  e2e/suites/actions-available/files-folders/generic.test.ts
  e2e/suites/actions-available/files-folders/test-data.ts
  e2e/suites/actions-available/libraries/test-data-libraries.ts
  e2e/suites/actions-available/special-permissions/other-permissions.ts
  e2e/suites/actions-available/special-permissions/test-data-permissions.ts
  e2e/suites/list-views/empty-list.test.ts
  e2e/suites/search/search-filters.test.ts
  package-lock.json
  package.json
  projects/aca-shared/store/src/actions/search.actions.ts
  projects/aca-testing-shared/src/components/search/filters/created-date-filter.ts
  projects/aca-testing-shared/src/components/search/filters/facet-filter.ts
  projects/aca-testing-shared/src/components/search/filters/generic-filter-panel.ts
  projects/aca-testing-shared/src/components/search/filters/generic-filter.ts
  projects/aca-testing-shared/src/components/search/filters/size-filter.ts
  projects/aca-testing-shared/src/components/search/index.ts
  projects/aca-testing-shared/src/components/search/search-filters.ts
  projects/aca-testing-shared/src/components/toolbar/toolbar.ts
  src/app.config.json
  src/app/components/search/search-results/search-results.component.html
  src/app/components/search/search-results/search-results.component.scss
  src/app/components/search/search-results/search-results.component.ts
  src/app/store/reducers/app.reducer.ts
  src/assets/app.extensions.json
  src/assets/i18n/ar.json
  src/assets/i18n/cs.json
  src/assets/i18n/da.json
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
  src/assets/i18n/fi.json
  src/assets/i18n/fr.json
  src/assets/i18n/it.json
  src/assets/i18n/ja.json
  src/assets/i18n/nb.json
  src/assets/i18n/nl.json
  src/assets/i18n/pl.json
  src/assets/i18n/pt-BR.json
  src/assets/i18n/ru.json
  src/assets/i18n/sv.json
  src/assets/i18n/zh-CN.json
Labels: PR: unreviewed

#2201 Update branch for ADF 32956 and JS-API 4.5.0-3637
  package-lock.json
  package.json
Labels: PR: unreviewed

#2202 Fix @alfresco
  scripts/travis/deploy/publish.sh
Labels: PR: unreviewed

#2204 [ACA-4497] allow user to extend the search configuration
  docs/extending/application-features.md
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  src/app.config.json
  src/assets/app.extensions.json
Labels: PR: unreviewed

#2205 Update branch for ADF 32963 and JS-API 4.5.0-3637
  package-lock.json
  package.json
Labels: PR: partially-approved
