Repository Alfresco/alfresco-content-app, pull requests merged in 2022-03, with the labels that each got.

#2463 [AAE-7660] file preview from info drawer
  e2e/suites/info-drawer/file-preview.test.ts
  projects/aca-testing-shared/src/components/info-drawer/info-drawer.ts
  projects/aca-testing-shared/src/components/search/search-input.ts
Labels: PR: partially-approved

#2467 [AAE-7832] Custom header text colour is not applied to user name
  projects/aca-shared/src/lib/components/tool-bar/toolbar-action/toolbar-action.component.scss
Labels: PR: partially-approved

#2471 [ACA-4574] ACA/ADW: Libraries toolbar disappears when no file matches…
  app/src/app.config.json.tpl
Labels: PR: partially-approved

#2473 Fix upstream
  .travis.yml
  scripts/trigger-travis.sh
Labels: PR: partially-approved

#2472 LOC-360 full fix - Updated UI files for ACA 2.6 release in 16 languages
  app/src/assets/i18n/ar.json
  app/src/assets/i18n/cs.json
  app/src/assets/i18n/da.json
  app/src/assets/i18n/de.json
  app/src/assets/i18n/es.json
  app/src/assets/i18n/fi.json
  app/src/assets/i18n/fr.json
  app/src/assets/i18n/it.json
  app/src/assets/i18n/ja.json
  app/src/assets/i18n/nb.json
  app/src/assets/i18n/nl.json
  app/src/assets/i18n/pl.json
  app/src/assets/i18n/pt-BR.json
  app/src/assets/i18n/ru.json
  app/src/assets/i18n/sv.json
  app/src/assets/i18n/zh-CN.json
Labels: PR: partially-approved

#2476 [ACS-2698] release 2.9.0
  app/src/app.config.json.tpl
  docs/audit/audit-info-2.9.0.md
  docs/changelog/changelog-2.9.0.md
  docs/licences/license-info-2.9.0.md
  package-lock.json
  package.json
  projects/aca-about/package.json
  projects/aca-settings/package.json
  projects/aca-shared/package.json
  projects/aca-testing-shared/package.json
  projects/adf-office-services-ext/package.json
Labels: PR: reviewed-approved

#2479 [AAE-7145] upgrade to Ngrx 10
  app/proxy.conf.js
  app/src/app/store/effects/app.effects.ts
  app/src/app/store/effects/contextmenu.effects.ts
  app/src/app/store/effects/download.effects.ts
  app/src/app/store/effects/favorite.effects.ts
  app/src/app/store/effects/library.effects.ts
  app/src/app/store/effects/node.effects.ts
  app/src/app/store/effects/search.effects.ts
  app/src/app/store/effects/template.effects.ts
  app/src/app/store/effects/upload.effects.ts
  app/src/app/store/effects/viewer.effects.ts
  docs/extending/dialog-actions.md
  docs/ja/extending/tutorials.md
  docs/ja/tutorials/dialog-actions.md
  docs/tutorials/dialog-actions.md
  package-lock.json
  package.json
  projects/aca-shared/store/src/effects/dialog.effects.ts
  projects/aca-shared/store/src/effects/router.effects.ts
  projects/aca-shared/store/src/effects/snackbar.effects.ts
  projects/adf-office-services-ext/src/lib/effects/aos.effects.ts
Labels: PR: unreviewed

#2482 [ci:force] Manually upgrade to latest js-api
  package-lock.json
  package.json
Labels: PR: unreviewed

#2487 [AAE-7238] fix performance issues and warnings in app
  .eslintignore
  app/src/app/components/info-drawer/info.drawer.module.ts
  app/src/app/components/toolbar/toolbar.module.ts
  app/src/app/extensions/core.extensions.module.ts
  package-lock.json
  package.json
Labels: PR: partially-approved

#2488 [AAE-8204] Remove tslint and codelizer
  .vscode/extensions.json
  package-lock.json
  package.json
  projects/aca-testing-shared/tslint.json
  tslint.json
Labels: PR: reviewed-approved

#2490 [AAE-8147] e2e jasmine callbacks removal
  e2e/suites/actions-available/files-folders/single-file-actions.test.ts
  e2e/suites/actions-available/libraries/library.test.ts
  e2e/suites/actions-available/new-menu/new-menu.test.ts
  e2e/suites/actions/copy-move/copy.test.ts
  e2e/suites/actions/copy-move/move.test.ts
  e2e/suites/actions/create/create-file-from-template.test.ts
  e2e/suites/actions/create/create-folder.test.ts
  e2e/suites/actions/create/create-library.test.ts
  e2e/suites/actions/delete/delete-undo-delete.test.ts
  e2e/suites/actions/delete/permanently-delete.test.ts
  e2e/suites/actions/delete/restore.test.ts
  e2e/suites/actions/edit/edit-folder.test.ts
  e2e/suites/actions/favorite/mark-favorite.test.ts
  e2e/suites/actions/share/unshare-file-search-results.test.ts
  e2e/suites/actions/share/unshare-file.test.ts
  e2e/suites/actions/upload-download/download.test.ts
  e2e/suites/actions/upload-download/upload-file.test.ts
  e2e/suites/actions/upload-download/upload-new-version.test.ts
  e2e/suites/application/general.test.ts
  e2e/suites/application/page-titles.test.ts
  e2e/suites/authentication/login.test.ts
  e2e/suites/authentication/logout.test.ts
  e2e/suites/extensions/ext-context-submenus.test.ts
  e2e/suites/extensions/ext-document-list.test.ts
  e2e/suites/extensions/ext-header.test.ts
  e2e/suites/extensions/ext-info-drawer.test.ts
  e2e/suites/extensions/ext-metadata.test.ts
  e2e/suites/extensions/ext-viewer.test.ts
  e2e/suites/info-drawer/comments.test.ts
  e2e/suites/info-drawer/file-folder-properties.test.ts
  e2e/suites/info-drawer/general.test.ts
  e2e/suites/info-drawer/library-properties.test.ts
  e2e/suites/list-views/empty-list.test.ts
  e2e/suites/list-views/favorites.test.ts
  e2e/suites/list-views/file-libraries.test.ts
  e2e/suites/list-views/generic-errors.test.ts
  e2e/suites/list-views/permissions.test.ts
  e2e/suites/list-views/personal-files.test.ts
  e2e/suites/list-views/recent-files.test.ts
  e2e/suites/list-views/shared-files.test.ts
  e2e/suites/list-views/tooltips.test.ts
  e2e/suites/navigation/breadcrumb.test.ts
  e2e/suites/navigation/sidebar.test.ts
  e2e/suites/navigation/single-click.test.ts
  e2e/suites/search/search-filters.test.ts
  e2e/suites/search/search-input.test.ts
  e2e/suites/search/search-results-files-folders.test.ts
  e2e/suites/search/search-results-general.test.ts
  e2e/suites/search/search-results-libraries.test.ts
  e2e/suites/search/search-sorting.test.ts
  e2e/suites/viewer/viewer-actions.test.ts
  e2e/suites/viewer/viewer-general.test.ts
Labels: PR: unreviewed
