Repository Alfresco/alfresco-content-app, pull requests merged in 2022-11, with the labels that each got.

#2752 [ACA-4622] Add focus for raised buttons
  app/src/app/ui/theme.scss
Labels: PR: partially-approved

#2754 [ACS-3886] Fix edit button being disabled when opening edit rule dialog initially
  projects/aca-folder-rules/src/lib/model/rule-action.model.ts
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.html
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts
Labels: PR: partially-approved

#2720 [ACS-3700] Pass mat menu items from external components to mat menu
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.ts
Labels: PR: partially-approved

#2753 [ACS-3744] Folder rules styling fixes
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/folder-rules.module.ts
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.scss
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/model/rule.model.ts
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/triggers/rule-triggers.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/triggers/rule-triggers.ui-component.ts
  projects/aca-folder-rules/src/lib/rules-list/rule-list.ui-component.html
  projects/aca-folder-rules/src/lib/rules-list/rule-list.ui-component.scss
  projects/aca-folder-rules/src/lib/rules-list/rule-list.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rules-list/rule-list.ui-component.ts
  projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.html
  projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.scss
  projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.ts
  projects/aca-folder-rules/src/lib/rules-list/rules-list.ui-component.html
  projects/aca-folder-rules/src/lib/rules-list/rules-list.ui-component.scss
  projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
Labels: PR: partially-approved

#2755 Update branch for ADF 36847 and JS-API 5.1.0 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2759 ACS-3545 fix e2e tests
  package-lock.json
  package.json
  projects/aca-testing-shared/src/components/info-drawer/info-drawer-comments-tab.ts
Labels: PR: partially-approved

#2757 [ACA-4618] Decouple ACA and Governance
  projects/aca-shared/rules/src/app.rules.spec.ts
  projects/aca-shared/rules/src/app.rules.ts
  projects/aca-shared/rules/src/public-api.ts
  projects/aca-shared/rules/src/record.rules.ts
  projects/adf-office-services-ext/src/lib/aos-extension.module.ts
  projects/adf-office-services-ext/src/lib/evaluators.spec.ts
  projects/adf-office-services-ext/src/lib/evaluators.ts
  projects/adf-office-services-ext/src/public-api.ts
Labels: PR: partially-approved

#2756 Update branch for ADF 36916 and JS-API 5.2.0-402 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2763 [ACS-3908] Add node version manager support
  .nvmrc
  docs/getting-started/README.md
  docs/getting-started/nvm.md
Labels: PR: partially-approved

#2764 ACS-3550 Fixed accessibility issues related with move and copy dialogs
  app/src/app/services/node-actions.service.ts
Labels: PR: partially-approved

#2767 Update branch for ADF 36948 and JS-API 5.2.0-409 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2769 [AAE-10766] upgrade to new About component
  app/src/app/services/content-management.service.spec.ts
  app/src/app/services/content-management.service.ts
  e2e/suites/actions/copy-move/copy.test.ts
  e2e/suites/actions/copy-move/move.test.ts
  e2e/suites/actions/delete/delete-undo-delete.test.ts
  e2e/suites/actions/delete/restore.test.ts
  package-lock.json
  package.json
  projects/aca-about/src/lib/about.component.html
  projects/aca-about/src/lib/about.component.ts
  projects/aca-shared/store/src/actions/snackbar.actions.ts
  projects/aca-shared/store/src/effects/snackbar.effects.ts
  projects/aca-testing-shared/src/pages/page.ts
Labels: PR: unreviewed

#2778 Revert snackbar changes
  app/src/app/services/content-management.service.spec.ts
  app/src/app/services/content-management.service.ts
  e2e/suites/actions/copy-move/copy.test.ts
  e2e/suites/actions/copy-move/move.test.ts
  e2e/suites/actions/delete/delete-undo-delete.test.ts
  e2e/suites/actions/delete/restore.test.ts
  package-lock.json
  package.json
  projects/aca-shared/store/src/actions/snackbar.actions.ts
  projects/aca-shared/store/src/effects/snackbar.effects.ts
  projects/aca-testing-shared/src/pages/page.ts
Labels: PR: partially-approved

#2777 [ACA-4624] - Add placeholder for input field in rules conditions
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-simple-condition.ui-component.html
Labels: PR: partially-approved

#2768 [ACS-3549] add role dialog in manage version dialog
  app/src/app/services/content-management.service.ts
Labels: PR: partially-approved

#2783 [ACS-4009] Fix pagination styling
  app/src/app/ui/theme.scss
Labels: PR: partially-approved

#2780 [ACS-3887] Rule set listing, including linked & inherited rules
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/folder-rules.module.ts
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.scss
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts
  projects/aca-folder-rules/src/lib/mock/node.mock.ts
  projects/aca-folder-rules/src/lib/mock/rule-sets.mock.ts
  projects/aca-folder-rules/src/lib/mock/rules.mock.ts
  projects/aca-folder-rules/src/lib/model/rule-set.model.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-list-item/rule-list-item.ui-component.html
  projects/aca-folder-rules/src/lib/rule-list/rule-list-item/rule-list-item.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-list/rule-list-item/rule-list-item.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.html
  projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-set-list/rule-set-list.ui-component.html
  projects/aca-folder-rules/src/lib/rule-list/rule-set-list/rule-set-list.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-list/rule-set-list/rule-set-list.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-set-list/rule-set-list.ui-component.ts
  projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.spec.ts
  projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
Labels: PR: partially-approved

#2770 Update branch for ADF 37028 and JS-API 5.2.0-419 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2786 add rebase workflow for PRs
  .github/workflows/rebase.yml
Labels: PR: partially-approved

#2791 [ACS-4014] Fix pre-commit hook for ACA
  .husky/pre-commit
  .lintstagedrc.json
  package.json
Labels: PR: partially-approved

#2787 [ACS-3971] updated pagination styling
  app/src/app/ui/custom-theme.scss
  app/src/app/ui/dynamic-theme/custom-theme.scss.tpl
  app/src/app/ui/overrides/adf-pagination.theme.scss
  app/src/app/ui/variables/variables.scss
Labels: PR: partially-approved

#2793 [ACS-4013] Fix pagination focus styling
  app/src/app/ui/mixins.scss
  app/src/app/ui/overrides/adf-pagination.theme.scss
  app/src/app/ui/theme.scss
Labels: PR: partially-approved

#2792 Update branch for ADF 37066 and JS-API 5.2.0-420 [ci:force]
  app/src/app/components/favorite-libraries/favorite-libraries.component.spec.ts
  app/src/app/components/favorites/favorites.component.spec.ts
  app/src/app/components/files/files.component.spec.ts
  app/src/app/components/libraries/libraries.component.spec.ts
  app/src/app/components/recent-files/recent-files.component.spec.ts
  app/src/app/components/shared-files/shared-files.component.spec.ts
  app/src/app/components/toolbar/toggle-favorite/toggle-favorite.component.spec.ts
  app/src/app/components/toolbar/toggle-join-library/toggle-join-library-button.component.ts
  app/src/app/components/toolbar/toggle-join-library/toggle-join-library.component.spec.ts
  app/src/app/components/trashcan/trashcan.component.spec.ts
  app/src/app/directives/directives.module.ts
  package-lock.json
  package.json
Labels: PR: partially-approved

#2794 Update branch for ADF 37074 and JS-API 5.2.0-423 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2785 [ACS-3640] Reverting reverted changes for a 11 y aca 881740 snackbar messages disappear without option to adjust timing
  app/src/app/services/content-management.service.spec.ts
  app/src/app/services/content-management.service.ts
  e2e/suites/actions/copy-move/copy.test.ts
  e2e/suites/actions/copy-move/move.test.ts
  e2e/suites/actions/delete/delete-undo-delete.test.ts
  e2e/suites/actions/delete/restore.test.ts
  package-lock.json
  package.json
  projects/aca-shared/store/src/actions/snackbar.actions.ts
  projects/aca-shared/store/src/effects/snackbar.effects.ts
  projects/aca-testing-shared/src/pages/page.ts
Labels: PR: unreviewed

#2803 ﻿[ACS-4010] Rule sets listing regrouping
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/folder-rules.module.ts
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts
  projects/aca-folder-rules/src/lib/mock/rule-sets.mock.ts
  projects/aca-folder-rules/src/lib/mock/rules.mock.ts
  projects/aca-folder-rules/src/lib/model/rule-grouping-item.model.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-list-grouping/rule-list-grouping.ui-component.html
  projects/aca-folder-rules/src/lib/rule-list/rule-list-grouping/rule-list-grouping.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-list/rule-list-grouping/rule-list-grouping.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-list-grouping/rule-list-grouping.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-list-item/rule-list-item.ui-component.html
  projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.html
  projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-set-list/rule-set-list.ui-component.html
  projects/aca-folder-rules/src/lib/rule-list/rule-set-list/rule-set-list.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-list/rule-set-list/rule-set-list.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-set-list/rule-set-list.ui-component.ts
  projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.spec.ts
  projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
Labels: PR: partially-approved

#2800 [ACS-3860] Folder rules - Node picker for action parameters of type "d:noderef"
  cspell.json
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts
  projects/aca-folder-rules/src/lib/mock/actions.mock.ts
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action-list.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action-list.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.html
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
Labels: PR: unreviewed

#2804 Update branch for ADF 37108 and JS-API 5.2.0-423 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2805 [ACS-4036] Move ay11 focus feature to one file and fix 'jumping'
  app/src/app/content-plugin/ui/custom-theme.scss
  app/src/app/content-plugin/ui/mixins.scss
  app/src/app/content-plugin/ui/overrides/adf-pagination.theme.scss
  app/src/app/content-plugin/ui/overrides/ay11.scss
  app/src/app/content-plugin/ui/theme.scss
Labels: PR: unreviewed

#2775 [ACS-3967] added open sans font to ACA
  angular.json
  app/src/app/content-plugin/ui/custom-theme.scss
  app/src/app/content-plugin/ui/variables/font-family.scss
  app/src/assets/fonts/OpenSans/OFL.txt
  app/src/assets/fonts/OpenSans/OpenSans-Bold.ttf
  app/src/assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
  app/src/assets/fonts/OpenSans/OpenSans-Light.ttf
  app/src/assets/fonts/OpenSans/OpenSans-Medium.ttf
  app/src/assets/fonts/OpenSans/OpenSans-Regular.ttf
  app/src/assets/fonts/OpenSans/OpenSans-SemiBold.ttf
  app/src/assets/fonts/OpenSans/OpenSans.css
  app/src/assets/fonts/muli/Muli-Black.ttf
  app/src/assets/fonts/muli/Muli-BlackItalic.ttf
  app/src/assets/fonts/muli/Muli-Bold.ttf
  app/src/assets/fonts/muli/Muli-BoldItalic.ttf
  app/src/assets/fonts/muli/Muli-ExtraBold.ttf
  app/src/assets/fonts/muli/Muli-ExtraBoldItalic.ttf
  app/src/assets/fonts/muli/Muli-ExtraLight.ttf
  app/src/assets/fonts/muli/Muli-ExtraLightItalic.ttf
  app/src/assets/fonts/muli/Muli-Italic.ttf
  app/src/assets/fonts/muli/Muli-Light.ttf
  app/src/assets/fonts/muli/Muli-LightItalic.ttf
  app/src/assets/fonts/muli/Muli-Regular.ttf
  app/src/assets/fonts/muli/Muli-SemiBold.ttf
  app/src/assets/fonts/muli/Muli-SemiBoldItalic.ttf
  app/src/assets/fonts/muli/muli.css
Labels: PR: unreviewed

#2809 [ACS-3758] 880526 modal is closed focus is not returned to trigger in the create new menu
  app/src/app/content-plugin/services/content-management.service.ts
  app/src/app/content-plugin/services/node-template.service.spec.ts
  app/src/app/content-plugin/services/node-template.service.ts
Labels: PR: partially-approved

#2807 Update branch for ADF 37122 and JS-API 5.2.0-423 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2810 [ACS-3513] [ACS-3515] Create, edit and delete rule set link
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/folder-rules.module.ts
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.scss
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-list-grouping/rule-list-grouping.ui-component.html
  projects/aca-folder-rules/src/lib/rule-list/rule-list-grouping/rule-list-grouping.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-list-grouping/rule-list-grouping.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-list-item/rule-list-item.ui-component.html
  projects/aca-folder-rules/src/lib/rule-list/rule-list-item/rule-list-item.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.html
  projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-list/rule-list/rule-list.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-set-picker/rule-set-picker.smart-component.html
  projects/aca-folder-rules/src/lib/rule-set-picker/rule-set-picker.smart-component.scss
  projects/aca-folder-rules/src/lib/rule-set-picker/rule-set-picker.smart-component.ts
  projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.ts
Labels: PR: partially-approved

#2811 Update branch for ADF 37162 and JS-API 5.2.0-435 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2808 [ACS-3895] ACA - Folder Rules: inherit rule sets toggle
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.scss
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts
  projects/aca-folder-rules/src/lib/mock/rules.mock.ts
  projects/aca-folder-rules/src/lib/model/rule.model.ts
  projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
Labels: PR: unreviewed

#2806 [AAE-10533] Replace shell with adf-shell
  app/src/app/app-shell/app-shell.module.ts
  app/src/app/app-shell/app-shell.routes.ts
  app/src/app/app-shell/components/shell/shell.component.html
  app/src/app/app-shell/components/shell/shell.component.scss
  app/src/app/app-shell/components/shell/shell.component.spec.ts
  app/src/app/app-shell/components/shell/shell.component.ts
  app/src/app/app-shell/index.ts
  app/src/app/app-shell/services/shell-app.service.ts
  app/src/app/app.module.ts
  docs/extending/app-shell.md
  tsconfig.adf.json
Labels: do not merge, PR: unreviewed

#2779 [ACS-3731] a11y zoom issues
  app/src/app/content-plugin/ui/application.scss
Labels: PR: unreviewed

#2812 Update branch for ADF 37197 and JS-API 5.2.0-435 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2818 Update branch for ADF 37208 and JS-API 5.2.0-435 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2819 Update branch for ADF 37220 and JS-API 5.2.0-443 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2823 Update branch for ADF 37225 and JS-API 5.2.0-445 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2824 [ACS-4630] Fix no different rule is selected when rule is deleted
  projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.spec.ts
  projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.ts
Labels: PR: unreviewed

#2822 [ACA-4627] Folder Rules - clicking on Manage Rules button does not fire the correct requests to the backend for inherited rules
  projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.spec.ts
  projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.ts
Labels: PR: partially-approved
