Repository Alfresco/alfresco-content-app, pull requests merged in 2022-01, with the labels that each got.

#2385 [AAE-6826] Create SCSS template
  app/src/app/components/create-menu/create-menu.component.scss
  app/src/app/components/main-action/main-action.component.scss
  app/src/app/ui/custom-theme-palettes.scss
  app/src/app/ui/custom-theme.scss
  app/src/app/ui/dynamic-theme/custom-palette-creator.scss
  app/src/app/ui/dynamic-theme/custom-theme-palettes.scss.tpl
  app/src/app/ui/dynamic-theme/index.scss
Labels: PR: reviewed-approved

#2381 Update branch for ADF 33975 and JS-API 4.8.0-4045 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2397 Update branch for ADF 34038 and JS-API 4.8.0-4074 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2403 [ACA-4548] Call the npm build to create replace app.config with envsub
  package.json
Labels: PR: partially-approved

#2402 [AAE-6811] Load custom theme
  app/src/app.config.json.tpl
  app/src/app/app.component.ts
  app/src/app/store/initial-state.ts
  projects/aca-shared/store/src/selectors/app.selectors.ts
  projects/aca-shared/store/src/states/app.state.ts
Labels: do not merge, PR: partially-approved

#2404 add missing PROVIDER env variable for docker
  Dockerfile
  docker/docker-entrypoint.d/30-sed-on-appconfig.sh
  docker/run.sh
Labels: PR: partially-approved

#2401 Update branch for ADF 34055 and JS-API 4.8.0-4074 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2415 Release 2.8.0
  docs/audit/audit-info-2.8.0.md
  docs/changelog/changelog-2.8.0.md
  docs/licences/license-info-2.8.0.md
  package-lock.json
  package.json
  projects/aca-about/package.json
  projects/aca-settings/package.json
  projects/aca-shared/package.json
  projects/aca-testing-shared/package.json
  projects/adf-office-services-ext/package.json
  scripts/generate-reports.sh
Labels: PR: unreviewed, PR: reviewed-approved
