Repository Alfresco/alfresco-content-app, pull requests merged in 2022-10, with the labels that each got.

#2678 Update branch for ADF 36495 and JS-API 5.1.0-343 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2680 Update branch for ADF 36502 and JS-API 5.1.0-349 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2685 [ACS-3596] Create / Update rule dialog - display errors
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.html
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
Labels: PR: partially-approved

#2687 [ACS-3315] Alfresco Administrators - private and moderate libraries-can't join to libraries issue resolved
  app/src/app/components/toolbar/toggle-join-library/toggle-join-library-menu.component.ts
Labels: PR: partially-approved

#2690 Update branch for ADF 36510 and JS-API 5.1.0-350 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2694 ACA-4615 view profile functionality should also be visible for SSO users
  app/src/app/components/view-profile/view-profile.guard.ts
Labels: PR: partially-approved

#2692 [ACA-3258] Edit rule dialog actions section
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/folder-rules.module.ts
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.scss
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts
  projects/aca-folder-rules/src/lib/mock/actions.mock.ts
  projects/aca-folder-rules/src/lib/model/rule-action.model.ts
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action-list.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action-list.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action-list.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action-list.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.html
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.scss
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
  projects/aca-folder-rules/src/lib/services/actions.service.spec.ts
  projects/aca-folder-rules/src/lib/services/actions.service.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts
Labels: PR: unreviewed

#2691 Update branch for ADF 36523 and JS-API 5.1.0-350 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2701 [ACS-3511] Update rules
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
Labels: PR: partially-approved

#2702 Update branch for ADF 36539 and JS-API 5.1.0-350 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2707 Update branch for ADF 36542 and JS-API 5.1.0-350 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2705 [ACS-3552] Accessibility fixes for CSV file issues
  app/src/app/components/files/files.component.html
  app/src/app/components/search/search-libraries-results/search-libraries-results.component.html
  app/src/app/components/search/search-results/search-results.component.html
  app/src/app/ui/theme.scss
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.html
Labels: PR: partially-approved

#2711 Update branch for ADF 36557 and JS-API 5.1.0-350 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2710 [ACS-3721] Change folder rules endpoints to private
  projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
Labels: PR: unreviewed, PR: draft, PR: partially-approved

#2714 Update branch for ADF 36563 and JS-API 5.1.0-350 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2695 [ACS-3548] accessibility issues fixed for ACS-3548
  app/src/app/components/details/details.component.html
  app/src/assets/i18n/en.json
Labels: PR: partially-approved

#2719 Update branch for ADF 36595 and JS-API 5.1.0-364 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2721 Update branch for ADF 36603 and JS-API 5.1.0-364 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2725 exclude flaky e2e: C306959
  e2e/protractor.excludes.json
Labels: PR: partially-approved

#2715 [ACS-3546] Fix for Create new folder a11y
  app/src/app/services/content-management.service.ts
Labels: PR: partially-approved

#2729 [acs-3548] fixed csv file issues(878577)
  app/src/app/app.routes.ts
  app/src/assets/i18n/en.json
Labels: PR: partially-approved

#2730 documentation fixes
  docs/README.md
  docs/getting-started/README.md
  docs/getting-started/building-from-source.md
  docs/getting-started/docker.md
  docs/getting-started/prerequisites.md
  docs/toc.md
Labels: PR: partially-approved

#2731 Update branch for ADF 36644 and JS-API 5.1.0-369 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2733 [ACS-3823] ACA: Folder rule conditions - wrong values passed as comparators
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-condition-comparators.ts
Labels: PR: partially-approved

#2732 Update branch for ADF 36666 and JS-API 5.1.0-369 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2738 [AAE-10984]: add path alias for adf auth second entry module
  tsconfig.adf.json
Labels: PR: partially-approved

#2735 Update branch for ADF 36718 and JS-API 5.1.0 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2740 [ACS-3668] Release 3.1.0
  app/src/app.config.json.tpl
  docs/audit/audit-info-3.1.0.md
  docs/changelog/changelog-3.1.0.md
  docs/licences/license-info-3.1.0.md
  package-lock.json
  package.json
Labels: PR: partially-approved

#2741 Update branch for ADF 36733 and JS-API 5.1.0 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2742 [ACS-3545] a11y aca metadata sidebar
  app/src/assets/i18n/en.json
  projects/aca-shared/src/lib/components/info-drawer/info-drawer.component.html
  projects/aca-shared/src/lib/components/info-drawer/shared-info-drawer.module.ts
Labels: PR: partially-approved

#2744 [ACS-3872] Disable boolean mode dropdown due to lack of OR in ACS
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.ui-component.ts
Labels: PR: partially-approved

#2745 Update branch for ADF 36751 and JS-API 5.1.0 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2746 Update branch for ADF 36765 and JS-API 5.1.0 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2747 Update branch for ADF 36790 and JS-API 5.1.0 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved
