Repository Alfresco/alfresco-content-app, pull requests merged in 2022-02, with the labels that each got.

#2417 [ACA-4546] Flaky ACA `Library actions` test
  e2e/suites/actions/library/library-actions.test.ts
  projects/aca-testing-shared/src/components/search/search-input.ts
Labels: PR: unreviewed

#2427 ACA-4565 - Temporary disabled failing tests
  e2e/protractor.excludes.json
Labels: do not merge, PR: unreviewed, PR: partially-approved

#2432 MNT-22687 - Fixed error in path when importing the new alfresco-offic…
  projects/aca-shared/src/public-api.ts
  projects/adf-office-services-ext/src/lib/aos-extension.module.ts
Labels: PR: partially-approved

#2438 Update branch for ADF 34191 and JS-API 4.8.0 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2451 [AAE-7355] automate manual C599174
  e2e/suites/info-drawer/file-folder-properties.test.ts
  projects/aca-testing-shared/src/components/info-drawer/info-drawer.ts
  projects/aca-testing-shared/src/components/search/search-input.ts
Labels: PR: unreviewed

#2431 [AAE-6822] Customize background and text colors
  app/src/app/components/search/search-input-control/search-input-control.component.scss
  app/src/app/ui/dynamic-theme/custom-background-color.scss
  app/src/app/ui/dynamic-theme/custom-text-color.scss
  app/src/app/ui/dynamic-theme/custom-theme.scss.tpl
  app/src/app/ui/dynamic-theme/theme-configuration.scss.tpl
  package-lock.json
  package.json
Labels: PR: unreviewed

#2452 ACA-4567 - Added ENV APP_CONFIG_PLUGIN_AOS=true in the Dockerfile
  Dockerfile
  docker/run.sh
Labels: PR: partially-approved

#2455 [AEE-6808] Align theme props with modelling app
  app/src/app/ui/dynamic-theme/custom-theme.scss.tpl
  app/src/app/ui/dynamic-theme/theme-configuration.scss.tpl
Labels: PR: partially-approved

#2461 [AAE-6808] Fix for loading external font
  app/src/app.config.json.tpl
  app/src/app/app.component.ts
Labels: PR: partially-approved

#2460 [AAE-7448] Automate remember sorting
  e2e/protractor.excludes.json
  e2e/suites/list-views/sort-list.test.ts
  projects/aca-testing-shared/src/components/data-table/data-table.ts
Labels: PR: partially-approved
