Repository Alfresco/alfresco-content-app, pull requests merged in 2022-08, with the labels that each got.

#2574 refine readme file
  README.md
Labels: PR: partially-approved

#2576 [ACS-3379] Fix unit tests for the visibility rules of the folder rules
  .travis.yml
  projects/aca-folder-rules/karma.conf.js
  projects/aca-folder-rules/src/lib/folder-rules.rules.spec.ts
Labels: PR: unreviewed

#2581 upgrade node.js for docker images
  Dockerfile
Labels: PR: partially-approved

#2578 [AAE-10029] - Change auth guard to support BPM configuration
  app/src/app/app.routes.ts
Labels: PR: unreviewed

#2583 remove unused project files
  projects/aca-about/ng-package.json
  projects/aca-about/package.json
  projects/aca-folder-rules/ng-package.json
  projects/aca-folder-rules/package.json
  projects/aca-settings/ng-package.json
  projects/aca-settings/package.json
  projects/aca-shared/ng-package.json
  projects/aca-shared/package.json
  projects/aca-testing-shared/package.json
  projects/adf-office-services-ext/ng-package.json
  projects/adf-office-services-ext/ngi.json
  projects/adf-office-services-ext/package.json
Labels: PR: unreviewed

#2582 Update branch for ADF 35854 and JS-API 4.12.0-244 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2597 ACA-4600-Edit-profile-functionality
  app/src/app/app.module.ts
  app/src/app/app.routes.ts
  app/src/app/components/view-profile/view-profile.component.html
  app/src/app/components/view-profile/view-profile.component.scss
  app/src/app/components/view-profile/view-profile.component.ts
  app/src/app/components/view-profile/view-profile.module.ts
  app/src/app/ui/variables/variables.scss
  app/src/assets/i18n/en.json
Labels: PR: partially-approved

#2595 Update branch for ADF 35967 and JS-API 4.12.0-244 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2599 Update branch for ADF 35996 and JS-API 4.12.0-244 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2585 [ACS-3257] Create / Update rules dialog condition section
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/folder-rules.module.ts
  projects/aca-folder-rules/src/lib/mock/conditions.mock.ts
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.validators.ts
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-condition-comparators.ts
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-condition-fields.ts
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-simple-condition.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-simple-condition.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-simple-condition.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-simple-condition.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
Labels: PR: unreviewed

#2602 Update branch for ADF 36043 and JS-API 4.12.0-244 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2603 [ACS-3256] Add trigger / "when" section to rule details & edit rule dialog
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/folder-rules.module.ts
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.scss
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts
  projects/aca-folder-rules/src/lib/mock/conditions.mock.ts
  projects/aca-folder-rules/src/lib/mock/rules.mock.ts
  projects/aca-folder-rules/src/lib/model/rule.model.ts
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-simple-condition.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-simple-condition.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-simple-condition.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.html
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/triggers/rule-triggers.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/triggers/rule-triggers.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/triggers/rule-triggers.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/validators/rule-composite-condition.validator.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
Labels: do not merge, PR: partially-approved

#2606 [AAE-10283] Fix deployment of content-ee and content-ee-apa with dyna…
  app/src/app/ui/dynamic-theme/custom-background-color.scss
  app/src/app/ui/dynamic-theme/custom-palette-creator.scss
  app/src/app/ui/dynamic-theme/custom-theme.scss.tpl
Labels: PR: partially-approved

#2609 [ACS-3219] Delete Rule
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.scss
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
Labels: PR: partially-approved

#2607 Update branch for ADF 36167 and JS-API 4.12.0-244 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed
