Repository Alfresco/alfresco-content-app, pull requests merged in 2022-12, with the labels that each got.

#2825 [ACA-4632] [ACA-4633] Fix error script dropdown not having any options + hide dropdown when isAsynchronous unchecked
  projects/aca-folder-rules/src/lib/mock/actions.mock.ts
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
Labels: PR: partially-approved

#2826 [ACS-4091] Folder rules: "Add simple workflow" action clears out parameters when trying to set destination folder
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.ts
Labels: PR: partially-approved

#2827 Update branch for ADF 37233 and JS-API 5.2.0-446 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2829 LOC-400 - Localized UI files for ACA 4.0 in 16 languages
  app/src/assets/i18n/ar.json
  app/src/assets/i18n/cs.json
  app/src/assets/i18n/da.json
  app/src/assets/i18n/de.json
  app/src/assets/i18n/es.json
  app/src/assets/i18n/fi.json
  app/src/assets/i18n/fr.json
  app/src/assets/i18n/it.json
  app/src/assets/i18n/ja.json
  app/src/assets/i18n/nb.json
  app/src/assets/i18n/nl.json
  app/src/assets/i18n/pl.json
  app/src/assets/i18n/pt-BR.json
  app/src/assets/i18n/ru.json
  app/src/assets/i18n/sv.json
  app/src/assets/i18n/zh-CN.json
  projects/aca-folder-rules/assets/i18n/ar.json
  projects/aca-folder-rules/assets/i18n/cs.json
  projects/aca-folder-rules/assets/i18n/da.json
  projects/aca-folder-rules/assets/i18n/de.json
  projects/aca-folder-rules/assets/i18n/es.json
  projects/aca-folder-rules/assets/i18n/fi.json
  projects/aca-folder-rules/assets/i18n/fr.json
  projects/aca-folder-rules/assets/i18n/it.json
  projects/aca-folder-rules/assets/i18n/ja.json
  projects/aca-folder-rules/assets/i18n/nb.json
  projects/aca-folder-rules/assets/i18n/nl.json
  projects/aca-folder-rules/assets/i18n/pl.json
  projects/aca-folder-rules/assets/i18n/pt-BR.json
  projects/aca-folder-rules/assets/i18n/ru.json
  projects/aca-folder-rules/assets/i18n/sv.json
  projects/aca-folder-rules/assets/i18n/zh-CN.json
Labels: PR: partially-approved

#2838 [AAE-11666] ACA 4.0.0-A.1 release changes
  app/src/app.config.json.tpl
  docs/audit/audit-info-4.0.0-A.1.md
  docs/changelog/changelog-4.0.0-A.1.md
  docs/licences/license-info-4.0.0-A.1.md
  package-lock.json
  package.json
Labels: PR: partially-approved

#2839 [ACS-4146] Folder Rules bug fix: An empty list for a child folder is displayed instead of an empty content template
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts
  projects/aca-folder-rules/src/lib/mock/rule-sets.mock.ts
Labels: PR: partially-approved

#2842 [ACA-4634] Folder Rules style fix: Edit and Delete Rule buttons disappear if rules have long description or name
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.scss
  projects/aca-folder-rules/src/lib/rule-list/rule-list-item/rule-list-item.ui-component.scss
Labels: PR: partially-approved

#2821 [ACS-3758] 880526 fix for modals which close was not returning to new button
  app/src/app/content-plugin/store/effects/upload.effects.spec.ts
  app/src/app/content-plugin/store/effects/upload.effects.ts
Labels: PR: partially-approved, next-version ➡️

#2845 [AAE-11695] update adf version
  e2e/protractor.excludes.json
  package-lock.json
  package.json
Labels: PR: unreviewed

#2837 [ACS-3757] returning focus to element from which they were opened
  app/src/app/content-plugin/components/common/toggle-shared/toggle-shared.component.html
  app/src/app/content-plugin/components/common/toggle-shared/toggle-shared.component.ts
  app/src/app/content-plugin/components/context-menu/context-menu.component.html
  app/src/app/content-plugin/components/context-menu/context-menu.component.spec.ts
  app/src/app/content-plugin/components/context-menu/context-menu.component.ts
  app/src/app/content-plugin/services/content-management.service.spec.ts
  app/src/app/content-plugin/services/content-management.service.ts
  app/src/app/content-plugin/services/node-actions.service.spec.ts
  app/src/app/content-plugin/services/node-actions.service.ts
  app/src/app/content-plugin/store/effects/download.effects.spec.ts
  app/src/app/content-plugin/store/effects/download.effects.ts
  app/src/app/content-plugin/store/effects/library.effects.ts
  app/src/app/content-plugin/store/effects/node.effects.spec.ts
  app/src/app/content-plugin/store/effects/node.effects.ts
  app/src/app/content-plugin/store/effects/upload.effects.ts
  package-lock.json
  package.json
  projects/aca-shared/src/lib/components/tool-bar/toolbar-button/toolbar-button.component.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu-item/toolbar-menu-item.component.ts
  projects/aca-shared/src/lib/components/tool-bar/toolbar-menu/toolbar-menu.component.html
  projects/aca-shared/src/lib/models/modal-configuration.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  projects/aca-shared/src/public-api.ts
  projects/aca-shared/store/src/actions/library.actions.ts
  projects/aca-shared/store/src/actions/node.actions.ts
  projects/aca-shared/store/src/actions/upload.actions.ts
Labels: PR: unreviewed

#2841 [ACA-4625] ADF linking in ACA
  .travis.yml
  README.md
  angular.json
  app/tsconfig.app.adf.json
  assets/link-adf-travis-console.png
  assets/link-adf-travis-stage.png
  scripts/ci/job_hooks/before_install.sh
  scripts/ci/jobs/check-link-adf.sh
  scripts/ci/partials/_adf-linking.sh
Labels: PR: unreviewed

#2784 [ACS-3751] New About Theme
  app/src/app/content-plugin/ui/custom-theme.scss
  app/src/app/content-plugin/ui/dynamic-theme/custom-theme.scss.tpl
  app/src/app/content-plugin/ui/overrides/adf-about.theme.scss
  app/src/app/content-plugin/ui/variables/variables.scss
Labels: PR: partially-approved

#2848 [AAE-11830] Changes required to address comment in APPS
  app/src/app/content-plugin/components/common/toggle-shared/toggle-shared.component.ts
  app/src/app/content-plugin/store/effects/download.effects.spec.ts
  app/src/app/content-plugin/store/effects/download.effects.ts
  app/src/app/content-plugin/store/effects/library.effects.ts
  app/src/app/content-plugin/store/effects/node.effects.ts
  app/src/app/content-plugin/store/effects/upload.effects.ts
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  projects/aca-shared/store/src/actions/library.actions.ts
  projects/aca-shared/store/src/actions/node.actions.ts
  projects/aca-shared/store/src/actions/upload.actions.ts
Labels: PR: partially-approved

#2849 [AAE-10656] Production version of ADW-APA miss the about page
  app/src/app/content-plugin/content-services-extension.module.ts
Labels: PR: partially-approved

#2847 Update branch for ADF 37470 and JS-API 5.3.0-477 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2853 [ACA-4625] Add ADF linking to unit tests and e2es
  .travis.yml
  angular.json
  app/tsconfig.spec.adf.json
  e2e/tsconfig.e2e.adf.json
  projects/aca-folder-rules/tsconfig.spec.adf.json
  projects/aca-settings/tsconfig.spec.adf.json
  projects/aca-shared/tsconfig.spec.adf.json
  projects/adf-office-services-ext/tsconfig.spec.adf.json
  protractor.conf.js
  scripts/ci/job_hooks/before_install.sh
  scripts/ci/jobs/affected-project-with.sh
  scripts/ci/partials/_adf-linking.sh
Labels: PR: partially-approved

#2855 Update branch for ADF 37482 and JS-API 5.3.0-477 [ci:force]
  app/src/app/content-plugin/components/info-drawer/comments-tab/comments-tab.component.spec.ts
  app/src/app/content-plugin/components/info-drawer/comments-tab/comments-tab.component.ts
  package-lock.json
  package.json
Labels: PR: unreviewed

#2851 [AAE-11496] - Make aca-shared and aca-folder-rules buidlable
  angular.json
  projects/aca-folder-rules/ng-package.json
  projects/aca-folder-rules/package.json
  projects/aca-folder-rules/tsconfig.lib.prod.json
  projects/aca-shared/ng-package.json
  projects/aca-shared/package.json
  projects/aca-shared/rules/src/app.rules.spec.ts
  projects/aca-shared/rules/src/app.rules.ts
  projects/aca-shared/src/lib/services/app.service.ts
  projects/aca-shared/store/src/actions/library.actions.ts
  projects/aca-shared/store/src/actions/node.actions.ts
  projects/aca-shared/store/src/actions/upload.actions.ts
  projects/aca-shared/store/src/models/modal-configuration.ts
  projects/aca-shared/tsconfig.lib.json
  projects/adf-office-services-ext/src/lib/aos-extension.service.ts
  projects/adf-office-services-ext/src/lib/effects/aos.effects.spec.ts
  projects/adf-office-services-ext/src/lib/utils.spec.ts
  projects/adf-office-services-ext/src/lib/utils.ts
  projects/adf-office-services-ext/src/public-api.ts
Labels: PR: unreviewed

#2857 Update branch for ADF 37505 and JS-API 5.3.0-483 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2858 Update branch for ADF 37548 and JS-API 5.3.0-492 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved
