Repository Alfresco/alfresco-content-app, pull requests merged in 2022-04, with the labels that each got.

#2492 [AAE-8201] - Add a way to hide libraries and secondary navbar sections
  .travis.yml
  Dockerfile
  README.md
  app/src/app.config.json.tpl
  app/src/app/extensions/core.extensions.module.ts
  app/src/app/services/content-service-extension.service.spec.ts
  app/src/app/services/content-service-extension.service.ts
  app/src/assets/app.extensions.json
  karma.conf.js
  projects/aca-shared/rules/src/app.rules.spec.ts
  projects/aca-shared/rules/src/app.rules.ts
Labels: PR: unreviewed

#2495 remove old logger implementation and deps
  package-lock.json
  package.json
  scripts/clireader/base-param.ts
  scripts/clireader/boolean-param.ts
  scripts/clireader/checkbox-param.ts
  scripts/clireader/cli-reader.ts
  scripts/clireader/input-param.ts
  scripts/clireader/list-param.ts
  scripts/clireader/params.ts
  tools/helpers/logger.js
Labels: PR: reviewed-approved

#2494 [AAE-8200] - Add a way to hide personal files and configure a landing…
  .travis.yml
  Dockerfile
  README.md
  app/src/app.config.json.tpl
  app/src/app/app.module.ts
  app/src/app/app.routes.ts
  app/src/app/components/header/header.component.html
  app/src/app/components/header/header.component.ts
  app/src/app/components/home/home.component.spec.ts
  app/src/app/components/home/home.component.ts
  app/src/assets/app.extensions.json
Labels: PR: unreviewed

#2506 [AAE-8202][AAE-8203] - Add a way to hide new button actions and searc…
  app/src/app/components/header/header.component.html
  app/src/app/components/header/header.component.spec.ts
  app/src/app/components/header/header.component.ts
  app/src/assets/app.extensions.json
Labels: PR: unreviewed

#2507 [ACA-4578] Exclude e2e connected to datatable sorting
  e2e/protractor.excludes.json
Labels: PR: partially-approved

#2511 [ACA-4578] Fix for datatable e2e-s
  e2e/protractor.excludes.json
  projects/aca-testing-shared/src/components/data-table/data-table.ts
Labels: PR: partially-approved

#2512 Update branch for ADF 34704 and JS-API 4.10.0-4289 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2515 [ACS-2838] Release 2.10.0
  app/src/app.config.json.tpl
  docs/audit/audit-info-2.10.0.md
  docs/licences/license-info-2.10.0.md
  package-lock.json
  package.json
  projects/aca-about/package.json
  projects/aca-settings/package.json
  projects/aca-shared/package.json
  projects/aca-testing-shared/package.json
  projects/adf-office-services-ext/package.json
Labels: PR: partially-approved
