Repository Alfresco/alfresco-content-app, pull requests merged in 2022-09, with the labels that each got.

#2612 [AAE-10512] Several icons cut off due to a fix introduced in Angular 14
  app/src/app/ui/application.scss
Labels: PR: partially-approved

#2613 fix test warnings for karma
  app/src/app/components/header/header.component.spec.ts
Labels: PR: partially-approved

#2617 [AAE-10540] cleanup version update script
  package-lock.json
  package.json
  scripts/update-package-version.sh
Labels: PR: unreviewed

#2619 LOC-383 - Updated UI files in 16 languages for ACA 2.13 release
  app/src/assets/i18n/ar.json
  app/src/assets/i18n/cs.json
  app/src/assets/i18n/da.json
  app/src/assets/i18n/de.json
  app/src/assets/i18n/es.json
  app/src/assets/i18n/fi.json
  app/src/assets/i18n/fr.json
  app/src/assets/i18n/it.json
  app/src/assets/i18n/ja.json
  app/src/assets/i18n/nb.json
  app/src/assets/i18n/nl.json
  app/src/assets/i18n/pl.json
  app/src/assets/i18n/pt-BR.json
  app/src/assets/i18n/ru.json
  app/src/assets/i18n/sv.json
  app/src/assets/i18n/zh-CN.json
  projects/aca-folder-rules/assets/i18n/ar.json
  projects/aca-folder-rules/assets/i18n/cs.json
  projects/aca-folder-rules/assets/i18n/da.json
  projects/aca-folder-rules/assets/i18n/de.json
  projects/aca-folder-rules/assets/i18n/es.json
  projects/aca-folder-rules/assets/i18n/fi.json
  projects/aca-folder-rules/assets/i18n/fr.json
  projects/aca-folder-rules/assets/i18n/it.json
  projects/aca-folder-rules/assets/i18n/ja.json
  projects/aca-folder-rules/assets/i18n/nb.json
  projects/aca-folder-rules/assets/i18n/nl.json
  projects/aca-folder-rules/assets/i18n/pl.json
  projects/aca-folder-rules/assets/i18n/pt-BR.json
  projects/aca-folder-rules/assets/i18n/ru.json
  projects/aca-folder-rules/assets/i18n/sv.json
  projects/aca-folder-rules/assets/i18n/zh-CN.json
Labels: PR: partially-approved

#2614 Update branch for ADF 36207 and JS-API 4.12.0-244 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2627 Release 3.0.0
  docs/audit/audit-info-3.0.0.md
  docs/changelog/changelog-3.0.0.md
  docs/licences/license-info-3.0.0.md
  package-lock.json
  package.json
Labels: PR: reviewed-approved

#2629 [AAE-6294] The list should be refreshed without allowing a used to se…
  app/src/app/components/files/files.component.html
  app/src/app/components/files/files.component.ts
  app/src/app/services/content-management.service.ts
  app/src/app/store/effects/node.effects.spec.ts
  app/src/app/store/effects/node.effects.ts
  app/src/app/store/initial-state.ts
  app/src/app/store/reducers/app.reducer.ts
  projects/aca-shared/store/src/actions/app-action-types.ts
  projects/aca-shared/store/src/actions/app.actions.ts
  projects/aca-shared/store/src/selectors/app.selectors.ts
  projects/aca-shared/store/src/states/app.state.ts
Labels: PR: partially-approved

#2601 ACA-4600-adding-input-validations-for-edit-profile
  app/src/app/components/view-profile/view-profile.component.html
  app/src/app/components/view-profile/view-profile.component.scss
  app/src/app/components/view-profile/view-profile.component.spec.ts
  app/src/app/components/view-profile/view-profile.component.ts
  app/src/assets/i18n/en.json
Labels: PR: partially-approved

#2621 Update branch for ADF 36300 and JS-API 5.1.0-317 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2624 cleanup unused theming
  angular.json
  app/src/styles.scss
Labels: PR: unreviewed

#2636 [ACS-3512] - ACA enable/disable rule from listing
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
  projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.html
  projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.scss
  projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.ts
  projects/aca-folder-rules/src/lib/rules-list/rules-list.ui-component.html
  projects/aca-folder-rules/src/lib/rules-list/rules-list.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rules-list/rules-list.ui-component.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
Labels: PR: partially-approved

#2643 Update branch for ADF 36308 and JS-API 5.1.0-317 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2611 [AAE-10253] It shouldn't be possible to right click in a drag&drop empty area
  projects/aca-shared/src/lib/directives/contextmenu/contextmenu.directive.spec.ts
  projects/aca-shared/src/lib/directives/contextmenu/contextmenu.directive.ts
Labels: PR: reviewed-changes-requested, PR: partially-approved

#2647 LOC-391 Fix for ACA-4606 - Updated strings in 16 languages
  app/src/assets/i18n/ar.json
  app/src/assets/i18n/cs.json
  app/src/assets/i18n/da.json
  app/src/assets/i18n/de.json
  app/src/assets/i18n/es.json
  app/src/assets/i18n/fi.json
  app/src/assets/i18n/fr.json
  app/src/assets/i18n/it.json
  app/src/assets/i18n/ja.json
  app/src/assets/i18n/nb.json
  app/src/assets/i18n/nl.json
  app/src/assets/i18n/pl.json
  app/src/assets/i18n/pt-BR.json
  app/src/assets/i18n/ru.json
  app/src/assets/i18n/sv.json
  app/src/assets/i18n/zh-CN.json
  projects/aca-folder-rules/assets/i18n/ar.json
  projects/aca-folder-rules/assets/i18n/cs.json
  projects/aca-folder-rules/assets/i18n/da.json
  projects/aca-folder-rules/assets/i18n/de.json
  projects/aca-folder-rules/assets/i18n/es.json
  projects/aca-folder-rules/assets/i18n/fi.json
  projects/aca-folder-rules/assets/i18n/fr.json
  projects/aca-folder-rules/assets/i18n/it.json
  projects/aca-folder-rules/assets/i18n/ja.json
  projects/aca-folder-rules/assets/i18n/nb.json
  projects/aca-folder-rules/assets/i18n/nl.json
  projects/aca-folder-rules/assets/i18n/pl.json
  projects/aca-folder-rules/assets/i18n/pt-BR.json
  projects/aca-folder-rules/assets/i18n/ru.json
  projects/aca-folder-rules/assets/i18n/sv.json
  projects/aca-folder-rules/assets/i18n/zh-CN.json
Labels: PR: partially-approved

#2649 Update branch for ADF 36323 and JS-API 5.1.0-322 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2651 [ACS-3259] Create / Update rule dialog - options section
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/folder-rules.module.ts
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
Labels: PR: partially-approved

#2650 Update branch for ADF 36346 and JS-API 5.1.0-322 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2657 Update branch for ADF 36353 and JS-API 5.1.0-322 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2652 [ACS-3537] - Fix accessibility issues in personal files
  app/src/app/app.component.spec.ts
  app/src/app/app.component.ts
  app/src/app/components/sidenav/components/expand-menu.component.html
Labels: PR: unreviewed

#2659 ACS-3544 Fix accessibility issues in trashcan
  app/src/app/components/common/location-link/location-link.component.ts
Labels: PR: partially-approved

#2662 ACA-4615 : Restrict Edit Profile functionality to ECM users only
  app/src/app/app.routes.ts
  app/src/app/components/view-profile/view-profile.guard.ts
Labels: PR: partially-approved

#2663 [ACS-3586] ACA/Folder Rules: Adding a rule to a Folder seems to break the Folder Rules UI
  projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
Labels: PR: partially-approved

#2665 [ACS-3548] heading added to resolve heading accessibility issue
  app/src/app/app.component.html
Labels: PR: partially-approved

#2669 [ACS-3575] Update FolderRulesService to provide a list of available aspects
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/model/aspect.model.ts
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.html
  projects/aca-folder-rules/src/lib/services/folder-rules.service.spec.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
Labels: PR: partially-approved

#2660 Update branch for ADF 36467 and JS-API 5.1.0-322 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2672 [ACS-3359] Rename boolean fields in rule API.
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/mock/rules.mock.ts
  projects/aca-folder-rules/src/lib/model/rule.model.ts
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.ts
  projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.html
  projects/aca-folder-rules/src/lib/rules-list/rule/rule-list-item.ui-component.ts
  projects/aca-folder-rules/src/lib/services/folder-rules.service.ts
Labels: PR: partially-approved

#2674 Update branch for ADF 36478 and JS-API 5.1.0-322 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved
