Repository Alfresco/alfresco-content-app, pull requests merged in 2023-05, with the labels that each got.

#3170 [ACS-4537] Make aca-about secondary entry of aca-content
  .github/actions/publish-libs/npm-publish.sh
  .github/actions/update-library-versions/update-lib-versions.sh
  app/project.json
  app/src/app/extensions.module.ts
  projects/aca-about/.eslintrc.js
  projects/aca-about/README.md
  projects/aca-about/karma.conf.js
  projects/aca-about/ng-package.json
  projects/aca-about/package.json
  projects/aca-about/project.json
  projects/aca-about/src/public-api.ts
  projects/aca-about/tsconfig.lib.json
  projects/aca-about/tsconfig.lib.prod.json
  projects/aca-about/tsconfig.spec.json
  projects/aca-content/about/assets/about.plugin.json
  projects/aca-content/about/ng-package.json
  projects/aca-content/about/src/about.component.html
  projects/aca-content/about/src/about.component.scss
  projects/aca-content/about/src/about.component.ts
  projects/aca-content/about/src/aca-about.module.ts
  projects/aca-content/about/src/dev-mode.tokens.ts
  projects/aca-content/about/src/package-json.token.ts
  projects/aca-content/about/src/public-api.ts
  scripts/gh/update/update-project.sh
  tsconfig.adf.json
  tsconfig.json
Labels: PR: partially-approved

#3163 [ACA-4646] Upgrade to Node 18
  .github/actions/before-e2e/action.yml
  .github/actions/run-e2e/action.yml
  .github/workflows/pull-request.yml
  .nvmrc
  README.md
  package-lock.json
  package.json
Labels: PR: unreviewed

#3179 [ACS-4537] Make aca-about secondary entry of aca-content
  .github/actions/publish-libs/npm-publish.sh
  .github/actions/update-library-versions/update-lib-versions.sh
  app/project.json
  app/src/app/extensions.module.ts
  projects/aca-about/.eslintrc.js
  projects/aca-about/README.md
  projects/aca-about/karma.conf.js
  projects/aca-about/ng-package.json
  projects/aca-about/package.json
  projects/aca-about/project.json
  projects/aca-about/src/public-api.ts
  projects/aca-about/tsconfig.lib.json
  projects/aca-about/tsconfig.lib.prod.json
  projects/aca-about/tsconfig.spec.json
  projects/aca-content/about/assets/about.plugin.json
  projects/aca-content/about/ng-package.json
  projects/aca-content/about/src/about.component.html
  projects/aca-content/about/src/about.component.scss
  projects/aca-content/about/src/about.component.ts
  projects/aca-content/about/src/aca-about.module.ts
  projects/aca-content/about/src/dev-mode.tokens.ts
  projects/aca-content/about/src/package-json.token.ts
  projects/aca-content/about/src/public-api.ts
  projects/aca-content/ng-package.json
  scripts/gh/update/update-project.sh
  tsconfig.adf.json
  tsconfig.json
Labels: PR: partially-approved

#3180 [ACS-4539] Make ms-office as secondary point of aca-content
  .github/actions/publish-libs/npm-publish.sh
  .github/actions/update-library-versions/update-lib-versions.sh
  .github/workflows/pull-request.yml
  app/project.json
  app/src/app/extensions.module.ts
  package-lock.json
  projects/aca-content/ms-office/LICENSE
  projects/aca-content/ms-office/assets/aos.plugin.json
  projects/aca-content/ms-office/assets/i18n/ar.json
  projects/aca-content/ms-office/assets/i18n/cs.json
  projects/aca-content/ms-office/assets/i18n/da.json
  projects/aca-content/ms-office/assets/i18n/de.json
  projects/aca-content/ms-office/assets/i18n/en.json
  projects/aca-content/ms-office/assets/i18n/es.json
  projects/aca-content/ms-office/assets/i18n/fi.json
  projects/aca-content/ms-office/assets/i18n/fr.json
  projects/aca-content/ms-office/assets/i18n/it.json
  projects/aca-content/ms-office/assets/i18n/ja.json
  projects/aca-content/ms-office/assets/i18n/nb.json
  projects/aca-content/ms-office/assets/i18n/nl.json
  projects/aca-content/ms-office/assets/i18n/pl.json
  projects/aca-content/ms-office/assets/i18n/pt-BR.json
  projects/aca-content/ms-office/assets/i18n/ru.json
  projects/aca-content/ms-office/assets/i18n/sv.json
  projects/aca-content/ms-office/assets/i18n/zh-CN.json
  projects/aca-content/ms-office/ng-package.json
  projects/aca-content/ms-office/src/actions/aos.actions.ts
  projects/aca-content/ms-office/src/aos-extension.module.ts
  projects/aca-content/ms-office/src/aos-extension.service.spec.ts
  projects/aca-content/ms-office/src/aos-extension.service.ts
  projects/aca-content/ms-office/src/effects/aos.effects.spec.ts
  projects/aca-content/ms-office/src/effects/aos.effects.ts
  projects/aca-content/ms-office/src/public-api.ts
  projects/aca-content/ng-package.json
  projects/aca-content/project.json
  projects/aca-content/test.ts
  projects/aca-content/tsconfig.lib.json
  projects/aca-content/tsconfig.spec.adf.json
  projects/aca-content/tsconfig.spec.json
  projects/adf-office-services-ext/.eslintrc.js
  projects/adf-office-services-ext/README.md
  projects/adf-office-services-ext/karma.conf.js
  projects/adf-office-services-ext/ng-package.json
  projects/adf-office-services-ext/package.json
  projects/adf-office-services-ext/project.json
  projects/adf-office-services-ext/src/test.ts
  projects/adf-office-services-ext/tsconfig.lib.json
  projects/adf-office-services-ext/tsconfig.lib.prod.json
  projects/adf-office-services-ext/tsconfig.spec.adf.json
  projects/adf-office-services-ext/tsconfig.spec.json
  scripts/gh/update/update-project.sh
  tsconfig.adf.json
  tsconfig.json
Labels: PR: partially-approved

#3112 [ADF-5532] Create upgrade211-30.md
  docs/upgrade-guide/upgrade211-30.md
Labels: do not merge, PR: unreviewed, PR: partially-approved
