Repository Alfresco/alfresco-content-app, pull requests merged in 2023-03, with the labels that each got.

#3021 Update branch for ADF 6.0.0-A.3 and JS-API 5.4.0 - Release Candidate [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#3022 [ACS-4741] User random user instead of admin in e2e
  e2e/suites/application/page-titles.test.ts
Labels: PR: reviewed-approved

#3024 [ACA-4666] Make finalize fail if any previous check fails
  .github/workflows/pull-request.yml
Labels: PR: partially-approved

#3025 Update branch for ADF 6.0.0-A.3-8334 and JS-API 5.4.0 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#3023 [AAE-12877] Fix - The left sidebar menu is not expanding after clicki…
  projects/aca-content/src/lib/components/header/header.component.spec.ts
  projects/aca-content/src/lib/components/layout/app-layout/app-layout.component.html
Labels: bug, PR: unreviewed, PR: partially-approved

#3027 [ACA-4653] Migrate release workflow to GHA
  .github/actions/before-install/action.yml
  .github/actions/git-tag/action.yml
  .github/actions/publish-image/action.yml
  .github/actions/publish-libs/action.yml
  .github/actions/setup/action.yml
  .github/workflows/aca-upstream.yml
  .github/workflows/release.yml
  .travis.yml
  scripts/travis/deploy/publish.sh
  scripts/travis/update/update-project.sh
Labels: PR: partially-approved

#3029 [ACA-4653] fix release actions
  .github/actions/git-tag/action.yml
  .github/actions/publish-image/action.yml
  .github/actions/publish-libs/action.yml
  .github/workflows/aca-upstream.yml
  .github/workflows/release.yml
  scripts/travis/deploy/publish.sh
Labels: PR: unreviewed

#3038 Release 4.0.0-A.3
  app/src/app.config.json.tpl
  docs/audit/audit-info-4.0.0-A.3.md
  docs/changelog/changelog-4.0.0-A.3.md
  docs/licences/license-info-4.0.0-A.3.md
  package-lock.json
  package.json
Labels: PR: partially-approved

#3039 [ACA-4649] GitHub Actions workflow fixes
  .github/actions/adf-linking/action.yml
  .github/actions/before-install/action.yml
  .github/actions/setup/action.yml
  .github/workflows/release.yml
Labels: PR: partially-approved

#3040 [ACA-4649] fix gha checks
  .github/actions/git-tag/action.yml
  .github/actions/publish-image/action.yml
  .github/actions/publish-libs/action.yml
Labels: PR: unreviewed

#3041 [ACA-4649] release workflow fixes
  .github/actions/publish-image/action.yml
  .github/workflows/release.yml
  scripts/travis/deploy/publish.sh
Labels: PR: partially-approved

#3042 [ACA-4649] fix lib publishing
  .github/actions/git-tag/action.yml
  .github/actions/publish-libs/action.yml
Labels: PR: unreviewed

#3043 [ACA-4649] release workflow enhancements
  .github/actions/publish-libs/action.yml
  .github/workflows/release.yml
  package.json
  scripts/gh/npm-publish.sh
  scripts/gh/update-lib-versions.sh
Labels: PR: partially-approved

#3044 [ACA-4649] update libs packages
  projects/aca-about/package.json
  projects/aca-content/package.json
  projects/aca-folder-rules/package.json
  projects/aca-preview/package.json
  projects/aca-shared/package.json
  projects/aca-testing-shared/package.json
  projects/aca-viewer/package.json
  projects/adf-office-services-ext/package.json
Labels: PR: partially-approved

#3045 release workflow fixes
  .github/actions/publish-libs/action.yml
  .github/actions/update-library-versions/action.yml
Labels: PR: partially-approved

#3046 fix update-library-versions action
  .github/actions/publish-libs/action.yml
  .github/actions/update-library-versions/action.yml
Labels: PR: unreviewed

#3048 gha: port tag fetch from ADF
  .github/actions/setup/action.yml
Labels: PR: unreviewed

#3049 fix gha setup
  .github/actions/setup/action.yml
Labels: PR: unreviewed

#3050 [AAE-12511] Fix oidc breaking changes
  tsconfig.adf.json
Labels: PR: partially-approved

#3052 [ACA-4668] cancel previous jobs in the workflow
  .github/workflows/pull-request.yml
Labels: PR: partially-approved

#2970 [AAE-10777] upgrade to latest ADF with common content services
  package-lock.json
  package.json
  projects/aca-about/src/lib/about.component.ts
  projects/aca-content/src/lib/aca-content.module.ts
  projects/aca-content/src/lib/components/common/user-info/user-info.component.ts
  projects/aca-content/src/lib/components/dl-custom-components/name-column/name-column.component.ts
  projects/aca-content/src/lib/components/favorites/favorites.component.ts
  projects/aca-content/src/lib/components/files/files.component.spec.ts
  projects/aca-content/src/lib/components/files/files.component.ts
  projects/aca-content/src/lib/components/layout/app-layout/app-layout.component.spec.ts
  projects/aca-content/src/lib/components/recent-files/recent-files.component.ts
  projects/aca-content/src/lib/components/search/search-results-row/search-results-row.component.ts
  projects/aca-content/src/lib/components/shared-files/shared-files.component.ts
  projects/aca-content/src/lib/components/view-profile/view-profile.component.spec.ts
  projects/aca-content/src/lib/services/content-management.service.spec.ts
  projects/aca-content/src/lib/services/content-management.service.ts
  projects/aca-content/src/lib/services/node-actions.service.ts
  projects/aca-content/src/lib/store/effects/download.effects.ts
  projects/aca-content/src/lib/store/effects/node.effects.spec.ts
  projects/aca-content/src/lib/store/effects/node.effects.ts
  projects/aca-content/src/lib/store/effects/upload.effects.spec.ts
  projects/aca-content/src/lib/store/effects/upload.effects.ts
  projects/aca-content/src/lib/testing/app-testing.module.ts
  projects/aca-content/src/lib/ui/colors.scss
  projects/aca-content/src/lib/ui/variables/variables.scss
  projects/aca-preview/src/lib/components/preview.component.spec.ts
  projects/aca-preview/src/lib/components/preview.component.ts
  projects/aca-shared/src/lib/services/app.service.spec.ts
  projects/aca-shared/src/lib/services/app.service.ts
  projects/aca-viewer/src/lib/components/viewer/viewer.component.ts
Labels: PR: unreviewed, breaking change

#3056 fix publishing upon PR merge
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: PR: unreviewed

#3055 [ACS-4792] provide support for style linting
  .github/workflows/pull-request.yml
  .stylelintrc.json
  .vscode/extensions.json
  .vscode/settings.json
  Dockerfile
  cspell.json
  package-lock.json
  package.json
  projects/aca-content/src/lib/components/create-menu/create-menu.component.scss
  projects/aca-content/src/lib/components/header/header.component.scss
  projects/aca-content/src/lib/components/node-version/node-version-form.component.scss
  projects/aca-content/src/lib/components/search/search-input-control/search-input-control.component.scss
  projects/aca-content/src/lib/components/search/search-input/search-input.component.scss
  projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.scss
  projects/aca-content/src/lib/components/search/search-results-row/search-results-row.component.scss
  projects/aca-content/src/lib/components/search/search-results/search-results.component.scss
  projects/aca-content/src/lib/components/sidenav/sidenav.component.scss
  projects/aca-content/src/lib/components/view-profile/view-profile.component.scss
  projects/aca-content/src/lib/ui/application.scss
  projects/aca-content/src/lib/ui/colors.scss
  projects/aca-content/src/lib/ui/custom-theme.scss
  projects/aca-content/src/lib/ui/dynamic-theme/custom-background-color.scss
  projects/aca-content/src/lib/ui/dynamic-theme/custom-palette-creator.scss
  projects/aca-content/src/lib/ui/dynamic-theme/custom-text-color.scss
  projects/aca-content/src/lib/ui/dynamic-theme/custom-theme-palettes.scss
  projects/aca-content/src/lib/ui/dynamic-theme/index.scss
  projects/aca-content/src/lib/ui/dynamic-theme/typography.scss
  projects/aca-content/src/lib/ui/mixins.scss
  projects/aca-content/src/lib/ui/overrides/adf-about.theme.scss
  projects/aca-content/src/lib/ui/overrides/adf-pagination.theme.scss
  projects/aca-content/src/lib/ui/overrides/ay11.scss
  projects/aca-content/src/lib/ui/theme.scss
  projects/aca-content/src/lib/ui/variables/variables.scss
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action-list.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-composite-condition.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/rule-details.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-list/rule-list-item/rule-list-item.ui-component.scss
  projects/aca-shared/src/lib/components/generic-error/generic-error.component.scss
  projects/aca-shared/src/lib/components/page-layout/page-layout.component.scss
Labels: PR: partially-approved

#3061 ACS-4814 - Use PR id for library publishing
  .github/actions/update-library-versions/action.yml
  .github/workflows/release.yml
Labels: PR: partially-approved

#3051 [ACA-4668] remove travis remains
  .eslintignore
  .github/actions/publish-image/action.yml
  .github/workflows/aca-upstream.yml
  app/project.metadata.json
  docs/extending/publish-to-npm.md
  e2e/e2e-config/utils/build-number.js
  scripts/app-config-replace.js
  scripts/ci/job_hooks/after_e2e.sh
  scripts/ci/job_hooks/before-playwright.sh
  scripts/ci/job_hooks/before_e2e.sh
  scripts/ci/job_hooks/before_install.sh
  scripts/ci/jobs/affected-project-with.sh
  scripts/ci/jobs/check-link-adf.sh
  scripts/ci/npm/publish-libs.sh
  scripts/ci/partials/_adf-linking.sh
  scripts/ci/utils/artifact-from-s3.sh
  scripts/ci/utils/artifact-to-s3.sh
  scripts/gh/docker-publish.sh
  scripts/gh/update/aca-same-commit-verify.js
  scripts/gh/update/pr-creator.js
  scripts/gh/update/update-project.sh
  scripts/travis/deploy/get-docker-image-tag-name.sh
  scripts/travis/release/git-tag.sh
  scripts/trigger-travis.sh
Labels: PR: partially-approved

#3060 [ACS-4441] Destination folder ids are now properly visible on View Rule Screen in Folder Rules
  cspell.json
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.scss
Labels: PR: partially-approved

#3063 [ACS-4837] improved spellcheck configuration
  cspell.json
Labels: PR: partially-approved

#3064 [ACS-4535] cleanup unused dependencies
  .github/actions/adf-linking/action.yml
  .github/actions/download-job-artifact/action.yml
  .github/actions/run-e2e/action.yml
  .github/actions/upload-job-artifact/action.yml
  angular.json
  e2e/lite-server-proxy.js
  package-lock.json
  package.json
Labels: PR: partially-approved

#3065 [ACS-4106] Removed default text for file upload placeholder
  projects/aca-folder-rules/assets/i18n/en.json
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.ts
Labels: PR: partially-approved

#3069 use dot as separator for minor v
  .github/actions/update-library-versions/action.yml
Labels: PR: partially-approved

#3068 [ACS-4535] rework docker publishing actions
  .github/actions/download-job-artifact/action.yml
  .github/actions/get-image-tag/action.yml
  .github/actions/publish-image/action.yml
  .github/actions/upload-job-artifact/action.yml
  .github/workflows/release.yml
  scripts/gh/docker-publish.sh
Labels: PR: unreviewed

#3084 [ACS-4922] Fix Playwright e2es after dependencies clean up [ACS-4535] cleanup unused dependencies
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: PR: partially-approved

#3071 cleanup GitHub actions
  .github/actions/after-e2e/action.yml
  .github/actions/before-e2e/action.yml
  .github/actions/before-install/action.yml
  .github/actions/download-job-artifact/action.yml
  .github/actions/get-image-tag/action.yml
  .github/actions/publish-libs/action.yml
  .github/actions/publish-libs/npm-publish.sh
  .github/actions/update-library-versions/action.yml
  .github/actions/update-library-versions/update-lib-versions.sh
  .github/actions/upload-job-artifact/action.yml
  .github/workflows/aca-upstream.yml
  .github/workflows/pull-request.yml
  .github/workflows/rebase.yml
  .github/workflows/release.yml
  scripts/run
  scripts/tsconfig.json
Labels: PR: partially-approved

#3080 [ACS-4436] comparator options set as Equals only when Encoding is selected in condition in Create/Edit a rule in Manage rules same as Share application
  projects/aca-folder-rules/src/lib/rule-details/conditions/rule-condition-fields.ts
Labels: PR: reviewed-approved

#3085 use angular serve for e2e
  .github/actions/before-e2e/action.yml
  .github/actions/run-e2e/action.yml
  README.md
Labels: PR: unreviewed

#3070 [ACS-4125] Add support for the tags search facet
  projects/aca-content/assets/app.extensions.json
Labels: PR: unreviewed

#3088 [ACA-4651] Fix build config in GHA
  .github/workflows/pull-request.yml
Labels: PR: partially-approved

#3089 [ACS-4951] fix pre-commit linting
  .lintstagedrc.json
Labels: PR: partially-approved

#3066 Update branch for ADF 6.0.0-A.3.8416 and JS-API 5.5.0-754 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#3093 [ACS-4126] Removed tags from libraries
  e2e/suites/list-views/file-libraries.test.ts
  e2e/suites/search/search-results-libraries.test.ts
  projects/aca-content/assets/app.extensions.json
Labels: PR: partially-approved

#3097 Update branch for ADF 6.0.0-A.3.8417 and JS-API 5.5.0-767 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#3100 [ACS-4968] Sort tags by usage in search facet
  projects/aca-content/assets/app.extensions.json
Labels: PR: partially-approved

#3101 Update branch for ADF 6.0.0-A.3.8427 and JS-API 5.5.0-767 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved
