Repository Alfresco/alfresco-content-app, pull requests merged in 2023-01, with the labels that each got.

#2860 move nodeupdate in nodeapiservice
  package-lock.json
  package.json
  projects/aca-content/src/lib/components/dl-custom-components/name-column/name-column.component.ts
  projects/aca-content/src/lib/components/preview/preview.component.spec.ts
  projects/aca-content/src/lib/components/preview/preview.component.ts
  projects/aca-content/src/lib/components/search/search-results-row/search-results-row.component.ts
  projects/aca-content/src/lib/components/viewer/viewer.component.ts
  projects/aca-content/src/lib/services/content-management.service.spec.ts
  projects/aca-content/src/lib/services/content-management.service.ts
Labels: PR: unreviewed

#2879 Fix adf configuration
  tsconfig.adf.json
Labels: PR: partially-approved

#2878 [ACA-4070] Add unit tests for linking rule sets
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.html
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/mock/node.mock.ts
  projects/aca-folder-rules/src/lib/mock/rule-sets.mock.ts
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.ts
  projects/aca-folder-rules/src/lib/rule-set-picker/rule-set-picker.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-set-picker/rule-set-picker.smart-component.ts
  projects/aca-folder-rules/src/lib/services/folder-rule-sets.service.spec.ts
Labels: PR: partially-approved

#2869 Update branch for ADF 37669 and JS-API 5.3.0-511 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2885 Update branch for ADF 37680 and JS-API 5.3.0-511 [ci:force]
  package-lock.json
  package.json
  projects/aca-shared/src/lib/services/app.service.spec.ts
Labels: PR: unreviewed

#2888 [ACS-4108] rule actions were showing id instead of names
  projects/aca-folder-rules/src/lib/rule-details/actions/rule-action.ui-component.ts
Labels: PR: partially-approved

#2887 Update branch for ADF 37695 and JS-API 5.3.0-514 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2891 [ACA-4648] Capitalised the 'r' in 'Manage rules'
  e2e/suites/actions-available/files-folders/test-data.ts
  projects/aca-folder-rules/assets/i18n/en.json
Labels: PR: partially-approved

#2890 [ACA-4645] Fix for shareActions e2es
  e2e/protractor.excludes.json
  e2e/suites/actions/share/share-file.test.ts
  e2e/suites/actions/share/unshare-file-search-results.test.ts
  projects/aca-testing-shared/src/components/toolbar/toolbar.ts
Labels: PR: unreviewed

#2892 Update branch for ADF 37730 and JS-API 5.3.0-520 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2901 Update branch for ADF github-run-3894886213 and JS-API 5.3.0-525 [ci:force]
  package-lock.json
  package.json
Labels: PR: unreviewed

#2899 [ACA-4633] Fix error script dropdown sometimes not having a label
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/options/rule-options.ui-component.spec.ts
Labels: PR: partially-approved

#2903 [AAE-12099] Process only UI is broken and all sections are shown
  projects/aca-content/src/lib/extensions/core.extensions.module.ts
Labels: PR: partially-approved

#2902 Update branch for ADF 6.0.0-A.1-3913456929 and JS-API 5.3.0-528 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2904 [ACA-4649] GHA linting and unit testing support
  .github/workflows/codeql-analysis.yml
  .github/workflows/test.yml
Labels: PR: partially-approved

#2875 [ACS-4075] - Folder Rules bugfix: Execute Script uses node ref picker instead of dropdown
  projects/aca-folder-rules/src/lib/folder-rules.module.ts
  projects/aca-folder-rules/src/lib/manage-rules/manage-rules.smart-component.ts
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.smart-component.spec.ts
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.ui-component.html
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.ui-component.scss
  projects/aca-folder-rules/src/lib/rule-details/edit-rule-dialog.ui-component.ts
Labels: PR: unreviewed

#2909 Update branch for ADF 6.0.0-A.1-3930016025 and JS-API 5.3.0-536 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2910 add missing linting for aca-content
  angular.json
  package.json
  projects/aca-content/.eslintrc.json
Labels: PR: partially-approved

#2911 Update branch for ADF 6.0.0-A.1-3932165443 and JS-API 5.3.0-536 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2913 [ACS-4417] fix the shared link datetime picker defaults
  app/src/app.config.json.tpl
  e2e/protractor.excludes.json
Labels: PR: unreviewed

#2917 LOC-406 - Updated UI files in 16 languages - aca-folder-rules
  projects/aca-folder-rules/assets/i18n/ar.json
  projects/aca-folder-rules/assets/i18n/cs.json
  projects/aca-folder-rules/assets/i18n/da.json
  projects/aca-folder-rules/assets/i18n/de.json
  projects/aca-folder-rules/assets/i18n/es.json
  projects/aca-folder-rules/assets/i18n/fi.json
  projects/aca-folder-rules/assets/i18n/fr.json
  projects/aca-folder-rules/assets/i18n/it.json
  projects/aca-folder-rules/assets/i18n/ja.json
  projects/aca-folder-rules/assets/i18n/nb.json
  projects/aca-folder-rules/assets/i18n/nl.json
  projects/aca-folder-rules/assets/i18n/pl.json
  projects/aca-folder-rules/assets/i18n/pt-BR.json
  projects/aca-folder-rules/assets/i18n/ru.json
  projects/aca-folder-rules/assets/i18n/sv.json
  projects/aca-folder-rules/assets/i18n/zh-CN.json
Labels: PR: partially-approved

#2915 Update branch for ADF 6.0.0-A.1-3960343939 and JS-API 5.3.0-539 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2922 Update branch for ADF 6.0.0-A.1-3975475084 and JS-API 5.3.0-539 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2923 Release 4.0.0-A.2
  app/src/app.config.json.tpl
  docs/audit/audit-info-4.0.0-A.2.md
  docs/changelog/changelog-4.0.0-A.2.md
  docs/licences/license-info-4.0.0-A.2.md
  package-lock.json
  package.json
Labels: PR: unreviewed

#2926 Update branch for ADF 6.0.0-A.2-3987832675 and JS-API 5.3.0 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2916 [AAE-11496] Make aca-shared buildable
  projects/aca-content/src/lib/aca-content.module.ts
  projects/aca-content/src/lib/components/details/details.component.ts
  projects/aca-content/src/lib/components/favorite-libraries/favorite-libraries.component.ts
  projects/aca-content/src/lib/components/favorites/favorites.component.ts
  projects/aca-content/src/lib/components/files/files.component.ts
  projects/aca-content/src/lib/components/libraries/libraries.component.ts
  projects/aca-content/src/lib/components/preview/preview.component.ts
  projects/aca-content/src/lib/components/recent-files/recent-files.component.ts
  projects/aca-content/src/lib/components/search/search-libraries-results/search-libraries-results.component.ts
  projects/aca-content/src/lib/components/search/search-results/search-results.component.ts
  projects/aca-content/src/lib/components/shared-files/shared-files.component.ts
  projects/aca-content/src/lib/components/trashcan/trashcan.component.ts
  projects/aca-shared/ng-package.json
  projects/aca-shared/src/lib/components/document-base-page/document-base-page.component.ts
  projects/aca-shared/src/lib/components/document-base-page/document-base-page.service.ts
  projects/aca-shared/src/lib/components/document-base-page/document-base-page.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  projects/aca-shared/src/public-api.ts
Labels: PR: partially-approved, next-version ➡️

#2880 [AAE-11496] Publish libraries to npm
  .travis.yml
  angular.json
  docs/extending/publish-to-npm.md
  package.json
  scripts/ci/npm/publish-libs.sh
Labels: PR: partially-approved

#2930 [AAE-11496] Publish npm package using https
  scripts/ci/npm/publish-libs.sh
Labels: PR: partially-approved

#2929 Update branch for ADF 6.0.0-A.2-4013873116 and JS-API 5.4.0-550 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2932 [AAE-11496] Remove npm deprecation strategy
  scripts/ci/npm/publish-libs.sh
Labels: PR: partially-approved

#2935 [AAE-11496] Build and publish adf-office-services-ext
  angular.json
  package.json
  projects/aca-shared/package.json
  projects/adf-office-services-ext/ng-package.json
  projects/adf-office-services-ext/package.json
  projects/adf-office-services-ext/tsconfig.lib.prod.json
  scripts/ci/npm/publish-libs.sh
Labels: PR: unreviewed, PR: partially-approved

#2934 Update branch for ADF 6.0.0-A.2-4027022400 and JS-API 5.4.0-550 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2942 [AAE-11496] Build and publish aca-about and aca-settings
  angular.json
  app/src/app/extensions.module.ts
  package.json
  projects/aca-about/ng-package.json
  projects/aca-about/package.json
  projects/aca-about/src/lib/about.component.html
  projects/aca-about/src/lib/about.component.ts
  projects/aca-about/src/lib/aca-about.module.ts
  projects/aca-about/src/lib/package-json.token.ts
  projects/aca-about/src/public-api.ts
  projects/aca-about/tsconfig.lib.prod.json
  projects/aca-settings/ng-package.json
  projects/aca-settings/package.json
  projects/aca-settings/tsconfig.lib.prod.json
  scripts/ci/npm/publish-libs.sh
Labels: PR: partially-approved

#2943 [AAE-11496] Publish aca-about and aca-settings with public access
  projects/aca-about/package.json
  projects/aca-settings/package.json
Labels: PR: partially-approved

#2941 Update branch for ADF 6.0.0-A.2-4032814591 and JS-API 5.4.0-561 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2946 Update branch for ADF 6.0.0-A.2-4046227848 and JS-API 5.4.0-561 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2949 Update branch for ADF 6.0.0-A.2-4049216756 and JS-API 5.4.0-561 [ci:force]
  package-lock.json
  package.json
Labels: PR: partially-approved

#2945 [AAE-11496] Publish aca-viewer and aca-preview
  .github/workflows/test.yml
  angular.json
  package.json
  projects/aca-content/src/lib/aca-content.module.ts
  projects/aca-content/src/lib/aca-content.routes.ts
  projects/aca-preview/.eslintrc.json
  projects/aca-preview/README.md
  projects/aca-preview/karma.conf.js
  projects/aca-preview/ng-package.json
  projects/aca-preview/package.json
  projects/aca-preview/src/lib/components/preview.component.html
  projects/aca-preview/src/lib/components/preview.component.scss
  projects/aca-preview/src/lib/components/preview.component.spec.ts
  projects/aca-preview/src/lib/components/preview.component.ts
  projects/aca-preview/src/lib/preview.module.ts
  projects/aca-preview/src/public-api.ts
  projects/aca-preview/src/test.ts
  projects/aca-preview/tsconfig.lib.json
  projects/aca-preview/tsconfig.lib.prod.json
  projects/aca-preview/tsconfig.spec.json
  projects/aca-viewer/.eslintrc.json
  projects/aca-viewer/README.md
  projects/aca-viewer/karma.conf.js
  projects/aca-viewer/ng-package.json
  projects/aca-viewer/package.json
  projects/aca-viewer/src/lib/components/viewer/viewer.component.html
  projects/aca-viewer/src/lib/components/viewer/viewer.component.scss
  projects/aca-viewer/src/lib/components/viewer/viewer.component.ts
  projects/aca-viewer/src/lib/viewer.module.ts
  projects/aca-viewer/src/public-api.ts
  projects/aca-viewer/src/test.ts
  projects/aca-viewer/tsconfig.lib.json
  projects/aca-viewer/tsconfig.lib.prod.json
  projects/aca-viewer/tsconfig.spec.json
  scripts/ci/npm/publish-libs.sh
  tsconfig.adf.json
  tsconfig.json
Labels: PR: unreviewed
