Repository Alfresco/alfresco-content-app, pull requests merged in 2024-07, with the labels that each got.

#3937 [ACS-8375] [ACA] [General] Selecting a checkbox gives a light green color on focus
  projects/aca-content/src/lib/ui/overrides/ay11.scss
Labels: angular

#3943 [ACS-8376] [ACA] manage rules multiple UI issues in create rule dialog
  projects/aca-content/folder-rules/src/rule-details/actions/rule-action-list.ui-component.scss
  projects/aca-content/src/lib/ui/theme.scss
Labels: angular

#3944 [ACS-8378] Fixed inputs having fill styling throughout ACA
  projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.html
  projects/aca-content/folder-rules/src/rule-details/conditions/rule-composite-condition.ui-component.scss
  projects/aca-content/folder-rules/src/rule-details/rule-details.ui-component.scss
  projects/aca-content/src/lib/ui/theme.scss
Labels: angular

#3945 [ACS-8377] Fixed alignment of icons in search input control
  projects/aca-content/src/lib/components/search/search-input/search-input.component.scss
Labels: angular

#3946 [ACS-8415] Sidenav labels are now grey
  projects/aca-content/src/lib/components/sidenav/sidenav.component.scss
Labels: angular

#3935 [ACS-8379] Fixed issue where icons in menus were coming as black after ng16 upgrade
  projects/aca-content/src/lib/ui/theme.scss
Labels: angular

#3967 [ACS-8259] Testing Angular 15 - Manage rule page issue
  projects/aca-content/folder-rules/src/rule-details/actions/rule-action-list.ui-component.scss
  projects/aca-content/folder-rules/src/rule-details/actions/rule-action.ui-component.scss
Labels: angular

#3968 [ACS-8446] [ACA] Testing Angular 15 - Create button has no bolded text
  projects/aca-shared/src/lib/components/toolbar/toolbar-action/toolbar-action.component.scss
Labels: angular

#3973 [ACS-8398] unit tests
  projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/agents-button/agents-button.component.spec.ts
  projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-input/search-ai-input.component.html
  projects/aca-content/src/lib/components/knowledge-retrieval/search-ai/search-ai-input/search-ai-input.component.spec.ts
Labels: ai

#3956 [ACS-8325] [Bulk Legal Hold] Create Bulk Actions Dropdown
  extension.schema.json
  projects/aca-content/assets/i18n/en.json
  projects/aca-content/src/lib/aca-content.module.ts
  projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.html
  projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.scss
  projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.spec.ts
  projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.ts
  projects/aca-content/src/lib/components/search/search-results/search-results.component.html
  projects/aca-content/src/lib/components/search/search-results/search-results.component.ts
  projects/aca-content/src/lib/store/reducers/app.reducer.ts
  projects/aca-shared/src/lib/components/document-base-page/document-base-page.component.ts
  projects/aca-shared/src/lib/models/types.ts
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
  projects/aca-shared/store/src/actions/app-action-types.ts
  projects/aca-shared/store/src/actions/app.actions.ts
  projects/aca-shared/store/src/selectors/app.selectors.ts
  projects/aca-shared/store/src/states/app.state.ts
Labels: Legal Holds

#3971 [ACS-8326] enable running actions from bulk dropdown and resetting selection
  projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.html
  projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.spec.ts
  projects/aca-content/src/lib/components/bulk-actions-dropdown/bulk-actions-dropdown.component.ts
  projects/aca-shared/src/lib/services/app.extension.service.spec.ts
  projects/aca-shared/src/lib/services/app.extension.service.ts
Labels: Legal Holds
